### ISSUE TITLE
Question about SDSS DR4 LRG likelihood

### ISSUE THREAD

**Issue by anicola** [brinckmann/montepython_public#1]
Hi,

I have a question regarding the SDSS DR4 LRG likelihood in MontePython. In Tegmark et al., 2006, the nonlinear power spectrum is modeled as 
P_gal(k) = (1+Qk^2)/(1+Ak) P_lin(k)
When I look at the likelihood code for mPk I cannot find that this factor is taken into account anywhere. Am I right or am I missing something? 

Thank you very much for your help!
All the best,
Andrina

**Comment by brinckmann** [comment]
Hi Andrina,
The SDSS DR4 LRG likelihood is a legacy likelihood and predates my involvement with MontePython, so I'm not very familiar with it, but I'll try to answer your question. The likelihood itself does not have the non-linear modelling that you mention from the Tegmark paper, so the question is in what way the data has been manipulated and what assumptions have gone into that. I would check that the data is the non-linear power spectrum as expected (rather than a linear power spectrum obtained from the observed non-linear power spectrum), and in that case I would think that you can fit the data using halofit. In any case, I would suggest instead using SDSS DR7 LRG, unless you have some reason for preferring the DR4 one?

Perhaps a MontePython user who has used the DR4 likelihood can provide better feedback!
Best,
Thejs

**Comment by anicola** [comment]
Dear Thejs,

Thank you so much for your very helpful reply. I will look into the SDSS DR7 likelihood in this case.

Thank you very much again!
All the best,
Andrina
