### ISSUE TITLE
Planck likelihood for lensing without 2018 data?

### ISSUE THREAD

**Issue by DinorahBarbosa** [brinckmann/montepython_public#103]
Hi guys, 

Fist time using the plc 2018 with MP and turns out the Planck_lensing data file in montepython/likelihoods/Planck_lensing only has options for 2013 and 2015 data. Which got me confused since every other likelihood available for 2018 data is correct. Anyone knows why is it like this?  

P.S. : In the base2018.param input file it also uses Planck_lensing

P.S.S: Trying to use Planck_highl_TT, Planck_lowl_TT and Planck_lowl_EE as well

**Comment by brinckmann** [comment]
Hi Dinorah,

We renamed all of the 2015 likelihoods to Planck15_*, so the old `Planck_lensing` likelihood became `Planck15_lensing`. The new Planck_lensing likelihood is for Planck 2018, you can see this in the .data file where the path is for plc_3.0:
`Planck_lensing.path_clik = os.path.join(data.path['clik'], '../../../baseline/plc_3.0/lensing/smicadx12_Dec5_ftl_mv2_ndclpp_p_teb_consext8.clik_lensing')`

Perhaps you didn't update your MontePython version correctly? We just released v3.3, so you should update to that instead of v3.2.

Best,
Thejs

**Comment by DinorahBarbosa** [comment]
Hi Thejs, 

I updated Monte Python just now and all is fine. Thanks!

**Comment by brinckmann** [comment]
Great! You may want to update again as I just pushed a bug fix affecting analyze (or apply the small fix yourself indicated in issue #98 ). If cloned from github you should be able to just pull the last change.

Best,
Thejs

**Comment by DinorahBarbosa** [comment]
Just did it :)
