### ISSUE TITLE
Failed to calculate covariance matrix

### ISSUE THREAD

**Issue by DinorahBarbosa** [brinckmann/montepython_public#108]
Hi all, 

I've been trying to run my model with Planck data for a couple of days but it keeps crashing. Since is the first run I've been using the following: 

```
srun python ~/montepython_public-3.3.1/montepython/MontePython.py run -p ~/montepython_public-3.3.1/input/planck2018.param -o ~/montepython_public-3.3.1/chains/planck2018
 --conf ~/montepython_public-3.3.1/planck2018.conf -N 40000 --update 50 --superupdate 20 

```
But then it keeps deleting all chains: 

`Step  510  chain  0 : Failed to calculate covariance matrix
`

I also can't analyze with info, since the chains have few points now. This is my .log file:

```
2020-02-09_10__1.txt	  Number of steps:1	 Steps accepted:1        acc = 1        min(-loglike) = 31569.20
2020-02-09_40000__1.txt   Number of steps:545    Steps accepted:140	 acc = 0.26     min(-loglike) = 4368.95
2020-02-09_40000__2.txt   Number of steps:626    Steps accepted:135	 acc = 0.22     min(-loglike) = 8387.41
2020-02-09_40000__3.txt   Number of steps:568    Steps accepted:150	 acc = 0.26     min(-loglike) = 7419.93
2020-02-09_40000__4.txt   Number of steps:573    Steps accepted:155	 acc = 0.27     min(-loglike) = 6156.46

```

Can someone explain what am I doing wrong?

**Comment by miug14** [comment]
Hi @DinorahBarbosa, may I ask what the problem was? I am experiencing something similar for all my chains and can't seem to figure out what is wrong... The chains runs fine but for some reason the covariance matrix is never updated and I get similar "Step 510 chain 0 : Failed to calculate covariance matrix" warnings.
Thank you!

**Comment by brinckmann** [comment]
There's a lot of possible explanations or things to do here:

1) You probably just need to let the chains run for longer. 510 steps per chain isn't a lot.

2) If the acceptance rate is very low your chains might be failing to converge and you might need to start over with better initial guesses for the sigmas input in the param file or a different covmat.

3) If you can't guess your way to a good starting guess for sigmas/covmat it can be hard to get initial accepted points. Then sometimes starting with smaller than expected sigmas or a small jumping factor set with the `-f <float>` flag (which essentially multiplies all the sigmas in the sampling to determine the range from which samples are drawn) can help get enough accepted points to compute an initial covmat. 2.4 is optimal for perfectly Gaussian posteriors to get the desired acceptance rate of about 25%, 1.9 is optimal for Planck.

But a low value of 0.1-1 can be useful initially to get some accepted points in order to force the code to compute a starting covmat. If you don't set the value too low then the superupdate algorithm (e.g. flag `--superupdate 20` ) can actually get you back to a good jumping factor after you compute an initial covmat. It won't be able to adjust from e.g. 0.1 to 2.4, but could probably go from 0.5 to 2.4. If you choose a very low value you might instead need to start over in a new chains directory with a normal jumping factor once you have a covmat you can begin the new run from.

4) You can try to force the code to compute a covmat with the flag `--want-covmat` when analyzing chains with info, but note that in a standard run MontePython will deliberately not compute a covmat early on because the chains haven't converged to the maximum likelihood and/or haven't managed to explore it well enough yet for computing a covmat to make sense. That said, the starting point for the covmat computation is arbitrarily chosen as max(R-1) < 3. There's not a lot to suspect that e.g. a value max(R-1) = 3.5 wouldn't make for a decent enough starting point.

5) If you had very good starting guesses it might happen that you never see the covmat updated at all. The automatic covmat update stops at max(R-1) < 0.3, so if the chains quickly reach that point it might never need to run. Normally this is a good thing, but occasionally it happens that the starting guesses are somewhat good, but not great, and the code gets stuck at a less than optimal R-1 (e.g. ~0.02-0.03, where you want to get to 0.01).

You can of course try to simply keep running the chains for longer hoping that the increased sample is enough, but if this is happening due to a slightly incorrect degeneracy direction between parameters in the input covmat, or a missing parameter in the input covmat, then you might not reach R-1 = 0.01 in a reasonable amount of time. In that case it can be useful to do as in 4) and run with the new covmat.

If you do this while the chains are running, they will automatically load the new covmat in the chains directory and proceed as if the code had updated the covmat itself at that point. The convergence will drop by a ton then, since the code automatically removes the non-markovian part of the chains (and anything before the covmat update is non-markovian), but might obtain final convergence more quickly than a slightly wrong covmat.

I hope some of this helps. Good luck!

Best,
Thejs

**Comment by miug14** [comment]
Dear Thejs,
Thank you very much for your thorough answer! What I am finding at the moment is that, independently of how long I run the chains for different models and different data combinations, the covmat is never updated. When I look at my cluster output file I don't even see the usual attempts of checking the Gelman rubin criteria, only several messages like "Step  108550  chain  0 : Failed to calculate covariance matrix". I am running around 10 chains just a normal scalar field model in class v2.9 on a slurm based cluster with OMP_NUM_THREADS=4. I am also using -f 1.5 with Planck likelihood and the Planck covmat and bestfit. I am not sure what could be wrong but this looks more like a numerical problem than a problem with the convergence of the chains themselves. I attach an example of an output file. I have tried repeating the chains in another cluster with an older version of MP and the covmat is updated without a problem. Do you think there could be some python/package incompatibility?

[1865378-Test_planck_run1.zip](https://github.com/brinckmann/montepython_public/files/6922834/1865378-Test_planck_run1.zip)

**Comment by brinckmann** [comment]
What happens if you try to analyze the chains manually? My suspicion is there's a problem with one or more of the chains due to the errors that the run is producing. If they have interfered with chain output, e.g. produced half-written lines, then it won't be able to analyze the chains. Analyzing manually should give you an idea of what the problem is.

If my suspicion is correct, then the manual solution is to either 1) find and remove the offending line(s) or 2) remove he offending chains. That should allow it to compute a new covmat.

Best,
Thejs

**Comment by miug14** [comment]
Dear Thejs,
Thank you again for your quick reply. I usually download the chains from the cluster and analyse them locally but after your suggestion I tried analysing the chains on the cluster and found error. After some digging this seems to be an incompatibility between Intel MPI and how MPI is built into slurm. I have contacted the IT maintenance services of the cluster I am using and will post any solution here in case anyone else is struggling with a similar problem.
Again, thank you for your help!
