### ISSUE TITLE
Missing library Error: classy.pyx file

### ISSUE THREAD

**Issue by RubenArjona** [brinckmann/montepython_public#109]
Hi,

I have installed at the hydra cluster of the IFT the Planck 2018 likelihoods, CLASS and MontePython.

In MontePython, when I run a script serially then I produce chains as expected. The problem comes when I submit a job to the cluster. Then I get the following error message:
"Missing Library Error: You must have compiled the classy.pyx file. Please go to
/path/to/class/python and run the command python setup.py build"

Following the above steps I have this message:
"running build
running build_ext
skipping 'path/class/python/../python/classy.c' Cython extension (up-to-date)"

but my problem still persists with the message: "Missing library Error ... " when trying to send a job to the cluster. I emphasize that I can produce chains when I run the script serially.

This is my script:

#!/bin/sh
#SBATCH -J MPtest
#SBATCH --partition=batch
#SBATCH --get-user-env
#SBATCH -o ./job.%j.out
#SBATCH -e ./job.%j.err
#SBATCH -N 2
#SBATCH -n 2
#SBATCH -t 3-00:00:00

export OMP_NUM_THREADS=8

prun python montepython/MontePython.py run -p input_RA/base2018TTTEEE.param -o chains_RA -N 15000

And this is part of what I have in .bashrc:

#Addition for canopy. Python 2.7
VIRTUAL_ENV_DISABLE_PROMPT=1 source /home/rarjona/.local/share/canopy/edm/envs/User/bin/activate
export PYTHONPATH=/home/rarjona/.local/share/canopy/edm/envs/User/lib/site_packages:$ PYTHONPATH

#Planck 2018 variables
source /home/rarjona/planck_2018/code/plc_3.0/plc-3.01/bin/clik_profile.sh

#MontePython-3.2
export PATH=/home/rarjona/montepython_public/:$PATH

Compiler versions:
My gcc version is: 4.8.3
My icc version is: 16.0.0
My python version is: 2.7.13 Entough

How can I solve this issue on sending jobs to the cluster?

Many thanks!
Rubén

**Comment by brinckmann** [comment]
Hi Rubén,

Can you verify that you use the same python version when compiling CLASS and when running MontePython? Specifically, that the compilation with CLASS wasn't done using Python 3, since you're running MontePython with v2.7 (although the latest MontePython version is also Python 3 compatible, so you really only need the versions to agree).

If this wasn't it then I will see if I can find my old notes from when we used MontePython on the Hydra cluster at the IFT Cosmology Tools school. 

Best,
Thejs

**Comment by RubenArjona** [comment]
Thank you for your comments. I have solved the issue using the default python version of the cluster.
