### ISSUE TITLE
AttributeError: 'classy.Class' object has no attribute 'N_ur'

### ISSUE THREAD

**Issue by RubenArjona** [brinckmann/montepython_public#115]
Hi,

I have created a new likelihood following the instructions found in: "https://monte-python.readthedocs.io/en/latest/likelihoods.html" and the lecture notes: "https://indico.cern.ch/event/688110/timetable/#20180425". 

I want to constraint the cosmo parameter 'N_ur' and in this new likelihood I call this parameter from CLASS as: cosmo.N_ur(). When I try to run MontePython I get the following error: "AttributeError: 'classy.Class' object has no attribute 'N_ur'. 

It seems that CLASS doesn't recognize 'N_ur', but that is strange because if I run MontePython with Planck or BAO data I get expected constraints on 'N_ur' and things work fine.

How can I solve this problem? 

Many thanks,
Rubén

**Comment by brinckmann** [comment]
Hi Rubén,

Calls to CLASS in the form cosmo.N_ur() call a function in the class wrapper, i.e. they have to be defined in `class_directory/python/classy.pyx`. You could add a function that retrieves N_ur, but I'm not sure how much sense that makes since N_ur is only non-zero if you set it in MontePython (unless you made some significant changes to CLASS). Probably what you want is to retrieve the value from MontePython with the syntax:
`data.cosmo_arguments['N_ur']`
if it is a fixed parameter, or
`data.mcmc_parameters['N_ur']['current']*data.mcmc_parameters['N_ur']['scale'])`
if it is a varying parameter. Thinking about it, the former should work in both cases, but if not then this is an alternative way to do the same thing.

Best,
Thejs

**Comment by RubenArjona** [comment]
It worked, many thanks!
