### ISSUE TITLE
Superupdate and removal of non-markovian points

### ISSUE THREAD

**Issue by flo1984** [brinckmann/montepython_public#122]
Hi everyone,

I am currently doing a run with the superupdate flag turned on. The run is currently in a stage where it is regularly updating the covariance matrix (I infer that from looking at the "Date-modified" time-stamp of the *.covmat file and changes in its size). When I analyze the chains, however, no non-markovian points are being removed.  I also checked the chain files and there is no instance of 'update proposal' found.

Is there a particular criterion on when a change in the covariance matrix should lead to the removal of steps? 

Thanks, Florian

(ps. I'm using version 3.3 and I use python3)

**Comment by brinckmann** [comment]
Hi Florian,

Sometimes there is a delay between when the master chain creates a new covmat and it is loaded and used, since this is done every some number of steps. Can you check again whether things appear normal now?

If you're saving the output and aren't running in silent or quiet mode you should also be able to see what is going on there, including when a new covmat is computed (or failed to be computed) and when a covmat is loaded. I always make sure to send the output to a file during a run so I can view it live rather than having to wait for a job to finish.

Best,
Thejs

**Comment by flo1984** [comment]
Hi Thejs, 
Thanks for your reply. 

Things still appear a little unusual with this run (I have a very similar run on a different machine with python2 environment and there everything is normal, i.e. after updating the covariance matrix a comment is included in the chain file). I now followed your advice to save the output in a txt file, so we should be seeing what is going on soon. 

Best, 
Florian

**Comment by brinckmann** [comment]
I'll do some tests for Python 3 to see whether update still works as intended. Thank you for the feedback! Let me know if you uncover any additional information on this as MontePython with Python 3 has not been thoroughly tested yet and still requires feedback from users! Thank you for the help!

Best,
Thejs
