### ISSUE TITLE
Segmentation Fault 11

### ISSUE THREAD

**Issue by arsalanadil** [brinckmann/montepython_public#124]
Hi everyone,

I'm trying to use MP with the Planck likelihood code but keep getting the following error:

`Deduced starting covariance matrix:`
(some covariance matrix here)
`Update routine is enabled with value 50 (recommended: 50)`
`This number is rescaled by cycle length 6 (N_slow + f_fast * N_fast) to 300`
`Segmentation fault: 11`

This error appears quite generically, for example with the sample base.param and the example.param files.

The installation with waf appears to be successful, and I believe path variables are set correctly. I configured waf with cfitsio v3.470 and intel MKL libraries. Worth noting is that the clik_example_C which comes with the PLC likelihood appears to run correctly as well. MP also works correctly with the JLA likelihood. 

I've mostly exhausted things to try and would appreciate any help anyone has to offer on this (maybe other people have encountered this before). Thanks!

Best wishes,
Arsalan

**Comment by brinckmann** [comment]
Hi Arsalan,

The best advice I can give is to start over from scratch and try to reinstall Planck (and possibly CLASS). I find in these cases it's usually because something went wrong with the installation, even if everything looks to be installed correctly. Take care that there are no old Planck-related egg files laying around causing problems either.

Best,
Thejs

**Comment by arsalanadil** [comment]
Hi Thejs,

Thanks for your prompt response. I was also feeling nudged in that direction, however I think the problem stems from the intel MKL library. I reinstalled the plc code, this time without MKL, and things worked. This could be a peculiarity for MacOS (the plc README suggest MKL for Linux). 

One quick question: would you know if, while configuring waf for the plc code, one needs to use a specific link line for intel MKL as specified on the link line advisor:
https://software.intel.com/en-us/articles/intel-mkl-link-line-advisor
as opposed to simply configuring with the `--lapack_mkl=$MKLROOT` argument?

Thanks!
Arsalan

**Comment by brinckmann** [comment]
If I understand correctly, you used lapack instead of mkl on macOS and it worked? I have never tried installing the planck likelihoods on a MacOS devise, so this is potentially quite interesting and something I'll keep in mind. That also means the answer to your question is I don't know! Thank you for replying with your findings!

best,
Thejs

**Comment by arsalanadil** [comment]
Correct, I uninstalled MKL completely to be sure that waf finds the default lapack library that ships with macOS. In the future, I'll try reinstalling PLC with the intel MKL in case there was an issue  with the MKL installation the first time around. But for now I want to reap the fruits of the successful installation! 

Thanks,
Arsalan
