### ISSUE TITLE
Running with fixed cosmological parameters and varying nuisance params

### ISSUE THREAD

**Issue by tsmith2** [brinckmann/montepython_public#148]
I am trying to run MP with fixed cosmological parameters but varying CMB nuisance parameters with the following datasets:

data.experiments=['Planck_highl_TTTEEE', 'Planck_lowl_EE', 'Planck_lowl_TT', 'Planck_lensing']

When I do this I get the following CLASS error:

classy.CosmoSevereError: 
Error in Class: No lensed Cl compute

I have tried to fix the cosmology parameters by either setting sigma = 0 for those parameters, or by setting their values using data.cosmo_arguments['X'] = Y. I have also explicitly included

data.cosmo_arguments['lensing']='yes'
data.cosmo_arguments['output'] = 'lCl,mPk'

in order to try to force the lensed Cls to be computed. 

One other thing to note: it appears as though this problem is specific to CLASS v. 2.9 (though I need to test that hypothesis a bit more). 

Any insights on how to write a .param file with fixed cosmology but varying nuisance parameters?

**Comment by brinckmann** [comment]
Hi,

I have no idea how to approach this or why it is a problem to fix all of the cosmo parameters since it apparently gets far enough to where it actually calls class. Do you have oversampling enabled? Maybe you could try sampling a cosmological parameter in a tiny range or add some huge oversampling number to only change the nuisance parameters.

Best,
Thejs
