### ISSUE TITLE
sigma values are 'nan' for certain parameter

### ISSUE THREAD

**Issue by talabadi** [brinckmann/montepython_public#149]
Hi,
The results of mpirun with 10 chains, 20,000 steps each, resulted with sigma value of 'nan' for one of the parameters.
the Gelman-Rubin value for the parameter was `R-1 value: 0.003849`

**Comment by brinckmann** [comment]
Hi,

This happens when the method for computing minimum credible intervals fails, which is usually due to poor convergence or non-Gaussian parameters. The easiest thing that sometimes works is to change the number of bins with the `--bins` flag. Otherwise the minimum credible intervals are computed in the `minimum_credible_intervals` function (line 1114-1225 in `montepython/analyze.py`) and you could try to change the method, e.g. using some scipy function or by adding a different algorithm.

Best,
Thejs
