### ISSUE TITLE
MultiNest seg fault

### ISSUE THREAD

**Issue by susanpyne** [brinckmann/montepython_public#15]
[Links back to issue raised on the old github page]
I'm getting segmentation faults when I use MontePython plus MultiNest - sometimes before any MultiNest output and sometimes after many lines of sample size/evidence values.
I'm using KiDS450xGAMA likelihood plus data consistent with van Uitert et al arXiv1706.05004, cosmic shear only. It runs fine with Metropolis-Hastings.
Please let me know any other information which would help.

**Comment by DeannaCH** [comment]
Hi,
Can you share your .param file with us, to make it easier to narrow down the issue?
Also, make sure you have the python package mpi4py installed and up-to-date, as MultiNest can be very picky if it isn't.
Cheers,
Deanna

**Comment by brinckmann** [comment]
Also, I think MultiNest can get a bit fussy about having many errors. If you're able to fix the issue giving you errors that may help as well. I suspect maybe the error is related to sampling tau_reio. If so, you can change sampling to z_reio instead (one is inferred from the other anyway), which often solves that particular problem.
Best,
Thejs

**Comment by susanpyne** [comment]
Hi Deanna


Here is my .param file. I'll look into mpi4py.


Thank you


Susan

________________________________

**Comment by susanpyne** [comment]
Just to end this issue (I hope). I have concluded that my problems are due to using HMCode with CLASS and so not caused by MontePython.  If I get any further problems I'll raise a new issue.

**Comment by lanny222** [comment]
@brinckmann 

any solution to this problem? ive tried using MultiNest as a solution to the multimodal problem i was having previously (https://github.com/brinckmann/montepython_public/issues/30) but i keep getting the error:



Error in Class: background_init(L:719) :error in background_solve(ppr,pba);
=>background_solve(L:1690) :error in generic_integrator(background_derivs, tau_start, tau_end, pvecback_integration, &bpaw, ppr->tol_background_integration, ppr->smallest_allowed_variation, &gi);
=>generic_integrator(L:112) :error in rkqs(&x, h, eps, &hdid, &hnext, derivs, parameters_and_workspace_for_derivs, pgi);
=>rkqs(L:156) :condition (xnew == *x) is true; stepsize underflow at x=9.684805e+01


Error in Class: background_init(L:719) :error in background_solve(ppr,pba);
=>background_solve(L:1672) :condition ((tau_end-tau_start)/tau_start < ppr->smallest_allowed_variation) is true; integration step: relative change in time =nan < machine precision : leads either to numerical error or infinite loop



Unlike when i dont pass MultiNest where the code finds solutions. I tried switching tau_reio to z_reio in the .param file and adjusting the values appropriately but nothing seems to work

**Comment by brinckmann** [comment]
Hi,
I'm not sure what the problem is, but maybe MultiNest is exploring an unphysical part of parameter space. Did you use parameter boundaries similar to those in input/example_ns.param ? MultiNest will sample the entire region specified by the boundaries, so you should typically choose something corresponding to a few sigma away from the best fit.

**Comment by lanny222** [comment]
@brinckmann still no luck with example_ns.param keep getting the error

Error in Class: thermodynamics_init(L:397) :error in thermodynamics_reionization(ppr,pba,pth,preco,preio,pvecback);
=>thermodynamics_reionization(L:1831) :error in thermodynamics_reionization_sample(ppr,pba,pth,preco,preio,pvecback);
=>thermodynamics_reionization_sample(L:2391) :condition (dz < ppr->smallest_allowed_variation) is true; stuck in the loop for reionization sampling, as if you were trying to impose a discontinuous evolution for xe(z)


Error in Class: background_init(L:719) :error in background_solve(ppr,pba);
=>background_solve(L:1672) :condition ((tau_end-tau_start)/tau_start < ppr->smallest_allowed_variation) is true; integration step: relative change in time =0.000000e+00 < machine precision : leads either to numerical error or infinite loop

**Comment by brinckmann** [comment]
I'm not sure I understand why you are getting an error related to reionization. I assume you're using the same parameter file as in #30, with only two varying cosmological parameters? With tau_reio fixed, it seems unlikely to return an issue, but try to fix z_reio instead of tau_reio (which is set by default when running CLASS with no tau_reio or z_reio parameter), i.e. with `data.cosmo_arguments['z_reio'] = 9.` (with whatever number you would like). Your new model does not affect reionization, is that correct?

Best,
Thejs

**Comment by lanny222** [comment]
@brinckmann 

No luck it seems, setting 'data.cosmo_arguments['z_reio'] = 10', still gives these errors 

Error in Class: thermodynamics_init(L:397) :error in thermodynamics_reionization(ppr,pba,pth,preco,preio,pvecback);
=>thermodynamics_reionization(L:1831) :error in thermodynamics_reionization_sample(ppr,pba,pth,preco,preio,pvecback);
=>thermodynamics_reionization_sample(L:2391) :condition (dz < ppr->smallest_allowed_variation) is true; stuck in the loop for reionization sampling, as if you were trying to impose a discontinuous evolution for xe(z)


Error in Class: background_init(L:719) :error in background_solve(ppr,pba);
=>background_solve(L:1672) :condition ((tau_end-tau_start)/tau_start < ppr->smallest_allowed_variation) is true; integration step: relative change in time =0.000000e+00 < machine precision : leads either to numerical error or infinite loop


Can't understand how it works well without MultiNest but doesn't with it enabled

**Comment by brinckmann** [comment]
My guess is this error happens regardless of the sampler, but since Metropolis-Hastings is more robust and won't always crash if it encounters errors and will instead reject points, you don't notice the problem. You can try to have a look at the output from the Metropolis-Hastings run, maybe you will find errors there. Also, I would suggest to take a close look at your CLASS implementation to see if there's a problem there.

Best,
Thejs

**Comment by ivandebono** [comment]
I came up against the problem of segmentation faults too. 

If you are running parallel processes with OpenMPI, try mpiexec -np 1. I don't know whether it slows down the calculation, or even what running multiple processes actually does when youn use Multinest (you don't get N chains corresponding to -np N like you do in a normal MontePython run). But it was the only way I could get it to complete a run.
