### ISSUE TITLE
Key error: cosmo

### ISSUE THREAD

**Issue by frompineve** [brinckmann/montepython_public#150]
Hi everyone,

I have been facing the following problem when trying to add a new background parameter to CLASS/Montepython.
Basically I want Montepython to scan over the logarithm of a certain new parameter x. So I define another parameter, which I call log10_x, then in the background.c I write:

pba->x=pow(10, pba->log10_x);

And of course I also add the parameters to the input.c, background.h files. When running CLASS everything works nicely as expected. 
The problem comes in when running Montepython. I added both log10_x and x to the classy wrapper. 
However, when running, I get:

Traceback (most recent call last):
  File "/cluster/home/frompi01/montepython/montepython/run.py", line 191, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/cluster/home/frompi01/montepython/montepython/initialise.py", line 67, in initialise
    data = Data(command_line, path)
  File "/cluster/home/frompi01/montepython/montepython/data.py", line 213, in __init__
    self.fill_mcmc_parameters()
  File "/cluster/home/frompi01/montepython/montepython/data.py", line 395, in fill_mcmc_parameters
    self.read_file(self.param, 'data')
  File "/cluster/home/frompi01/montepython/montepython/data.py", line 550, in read_file
    exec(line.replace(structure+'.', 'self.').rstrip())
  File "<string>", line 1, in <module>
KeyError: 'cosmo'

The error arises only when using log10_x rather than x, since Montepython works fine with just x as a cosmo parameter. It is not due to the .param file, as I tried to fix log10_x to a certain value and still the code does not work. 

Does anybody here have any suggestion on how to overcome this problem? I guess it has to be something missing in classy, but I cannot figure out what exactly since I just followed the same procedure as with the other parameters.

Thank you!
Best

**Comment by brinckmann** [comment]
Hi,

I'm not really sure what the problem is here, but the montepython/data.py file has examples of parameters with a log conversion, e.g. line 907-90:
```
            elif elem == 'log10N_dg':
                self.cosmo_arguments['N_dg'] = 10**(self.cosmo_arguments[elem])
                del self.cosmo_arguments[elem]
```
You can add a similar elif condition for your parameter, allowing you to sample logarithmically while passing a non-log value to CLASS. I.e. you would add your log10_x as a parameter in the .param file, sampling across log space (e.g. from 0 to 10 representing 10**0 to 10**10), which is then converted in data.py to non-log before being passed to CLASS. E.g. you would replace 'N_dg' with 'x' and 'log10N_dg' with 'log10_x'.

Best,
Thejs
