### ISSUE TITLE
param file for scf mode (solved)

### ISSUE THREAD

**Issue by nkhadka21** [brinckmann/montepython_public#158]
Hi all,
I am new in montepython/class. I am trying to use montepython to extract cosmological and SCF potential parameters but I could not write any proper .param file for the SCF model. Could you please suggest me how to enter scf_parameters in the .param file? I tried scf_parameters = 10,0,0,0,100,0 as instructed in explanatory.ini file but it did not work. Any suggestions will be appreciated.

Thank you,

Narayan

**Comment by arsalanadil** [comment]
Hi Narayan,

You might find the following post helpful for dealing with passing scf parameters via montepython:
https://github.com/baudren/montepython_public/issues/54

Note also that you will need to set data.cosmo_arguments['scf_tuning_index'] = whatever-your-tuning-parameter-is, and data.cosmo_arguments['attractor_ic_scf'] = yes/no depending on your model

Hope this helps,
Arsalan

**Comment by nkhadk** [comment]
Hi Arsalan,
Thank you so much for your help. In baudren#54, it says count starts from 1, but in background.c and input.c, count for scf_parameters starts from zero like scf_parameters[0],....Do I need to change that in background.c and input .c file?

Narayan

**Comment by shan15noob** [comment]
Hi nkhadk,

Did you resolve your error?  Can you share how was it resolved ? If that is possible? I am facing the same problem.

regards,
shan

**Comment by ajcosmology** [comment]
Hey, did you manage to solve the problem? I am also facing the same problem. Can you please share the input .params file?

Thanks,
Alex

**Comment by brinckmann** [comment]
Hi Alex,

As mentioned in replies here and elsewhere, it is explained on the old MontePython github in issue https://github.com/baudren/montepython_public/issues/54 .

To answer the question some have had on here, the first parameter with `scf_paramaeters__1` corresponds to CLASS index `scf_parameters[0]` .

If you just want to fix all the parameters then e.g.
`data.cosmo_arguments['scf_parameters'] = '10,0,0,0,0,1e-4,0'`
should work. If you need to fix some and vary others (as is often the case) then you have to use the answer by Thomas Tram in issue https://github.com/baudren/montepython_public/issues/54 , where setting the sigma to 0 means you don't vary the parameters. MontePython will gather the numbers into a list in `montepython/data.py` at the appropriate point, when the varying parameters have been sampled, that is then passed to CLASS.

I think by default scf_parmaters has 6 entries, not 7 as in that example, make sure you pass the correct amount of numbers for your model, whether you use the cosmo_arguments method (only works for fixing everything) or the cosmo_parameters method mentioned by Thomas Tram. 

Best,
Thejs

**Comment by HafizInam786** [comment]
HY everyone, I need help regarding scf parameters. my classFreeSF is working and montepython, but when I run param files, all paramters are ok, but in terminal the error is " scf parameters did not read by class" i do everything to update ClassFreeSF. All other paramters read by class, but not scf why, can anyone help this?

**Comment by awaisipnphy-ui** [comment]
#  SFDM - WORKING VERSION

data.experiments = ['bao_desi_dr2']

# --- Cosmological parameters ---
# Standard parameters with Planck-like values
data.parameters['omega_b']       = [0.02237,  0.020,  0.025,  0.0001, 1, 'cosmo']
data.parameters['h']             = [0.6736,   0.60,   0.75,   0.01,   1, 'cosmo']
data.parameters['n_s']           = [0.9649,   0.94,   0.99,   0.005,  1, 'cosmo']
data.parameters['ln10^{10}A_s']  = [3.044,    2.7,    3.3,    0.02,   1, 'cosmo']
data.parameters['tau_reio']      = [0.0544,   0.04,   0.08,   0.005,  1, 'cosmo']

# SFDM parameters - CRITICAL FIXES
data.parameters['m_scf']         = [-23.0,   -26.0,  -18.0,  1.0,    1, 'cosmo']    # Log scale for mass!
data.parameters['Omega0_scf']    = [0.315,   0.20,   0.40,   0.01,   1, 'cosmo']    # Total matter density


# --- Fixed parameters -
data.parameters['omega_cdm']     = [1e-10,    1e-10,  1e-10,  0,      1, 'fixed']
data.parameters['YHe']           = [0.2454,   0.2454, 0.2454, 0,      1, 'fixed']
data.parameters['Omega_k']       = [0.0,      0.0,    0.0,    0,      1, 'fixed']
data.parameters['N_ur']          = [2.0328,   2.0328, 2.0328, 0,      1, 'fixed']
data.parameters['N_ncdm']        = [0,        0,      0,      0,      1, 'fixed']
data.parameters['T_cmb']         = [2.7255,   2.7255, 2.7255, 0,      1, 'fixed']

# --- Sampler setup ---

data.sampler = 'MH'
data.N = 100
data.update = 10
data.proposal_scale = 2.0  # Reduced for stability
data.temperature = 1.0
data.covmat = 'auto'

# --- Output ---

data.output_root = 'chains/sfdm_working'
data.print_level = 1

Hi I hope you all are doing well. when I run this parameter file I got the below error is there anyone help us to remove this error.

python3 montepython/MontePython.py run     -p input/sfdm_corrected.param     -o chains/sfdm_corrected     -N 1000
 /!\ PyMultiNest detected but MultiNest likely not installed correctly. You can
     safely ignore this if not running with option -m NS
 /!\ Appending to an existing folder: using the log.param instead of
     input/sfdm_corrected.param
Running Monte Python v3.6.1

with CLASS v2.5.0

Testing likelihoods for:
 ->bao_desi_dr2

Creating chains/sfdm_corrected/2025-11-18_1000__1.txt


Deduced starting covariance matrix:

['omega_b', 'h', 'n_s', 'ln10^{10}A_s', 'tau_reio', 'm_scf', 'Omega0_scf']
[[1.0e-08 0.0e+00 0.0e+00 0.0e+00 0.0e+00 0.0e+00 0.0e+00]
 [0.0e+00 1.0e-04 0.0e+00 0.0e+00 0.0e+00 0.0e+00 0.0e+00]
 [0.0e+00 0.0e+00 2.5e-05 0.0e+00 0.0e+00 0.0e+00 0.0e+00]
 [0.0e+00 0.0e+00 0.0e+00 4.0e-04 0.0e+00 0.0e+00 0.0e+00]
 [0.0e+00 0.0e+00 0.0e+00 0.0e+00 2.5e-05 0.0e+00 0.0e+00]
 [0.0e+00 0.0e+00 0.0e+00 0.0e+00 0.0e+00 1.0e+00 0.0e+00]
 [0.0e+00 0.0e+00 0.0e+00 0.0e+00 0.0e+00 0.0e+00 1.0e-04]]
Update routine is enabled with value 50 (recommended: 50)
This number is rescaled by cycle length 7 (N_slow + f_fast * N_fast) to 350
Traceback (most recent call last):
  File "/home/qarni/montepython_public/montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/qarni/montepython_public/montepython/run.py", line 45, in run
    sampler.run(cosmo, data, command_line)
  File "/home/qarni/montepython_public/montepython/sampler.py", line 46, in run
    mcmc.chain(cosmo, data, command_line)
  File "/home/qarni/montepython_public/montepython/mcmc.py", line 474, in chain
    loglike = sampler.compute_lkl(cosmo, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/qarni/montepython_public/montepython/sampler.py", line 747, in compute_lkl
    cosmo.compute()
  File "classy.pyx", line 347, in classy.Class.compute
TypeError: sequence item 0: expected str instance, bytes found
(base) qarni@qarni-HP-EliteBook-840-G7-Notebook-PC:~/montepython_public$
