### ISSUE TITLE
using m_s_eff in param file

### ISSUE THREAD

**Issue by ravi398** [brinckmann/montepython_public#160]
while we use m_s_eff ,it gives an error showing that 
deg_ncdm__2 is not read by class.
what could be the posiible solution?
thanks 
Ravi kumar sharma

**Comment by ravi398** [comment]
its actually giving ''key error'' about deg_ncdm__2.if we put data.arguments['deg_ncdm__2']=1 then it gives deg_ncdm__2 is not read by class.

**Comment by brinckmann** [comment]
Can you please say how you set all parameters related to ncdm and m_s_eff in the param file?

Best,
Thejs

**Comment by ravi398** [comment]
Thank you for your reply 
data.parameters['m_s_eff']     = [  3,  0, 10,      0.5,    1, 'cosmo']
data.cosmo_arguments['N_ur'] = 0.00641
data.cosmo_arguments['N_ncdm'] = 2
#data.cosmo_arguments['m_ncdm'] = 0.06
data.cosmo_arguments['T_ncdm'] = '0.71611,4.23418'
data.cosmo_arguments['deg_ncdm'] ='3,1'



error message
Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/ravi/mt/montepython/run.py", line 45, in run
    sampler.run(cosmo, data, command_line)
  File "/home/ravi/mt/montepython/sampler.py", line 46, in run
    mcmc.chain(cosmo, data, command_line)
  File "/home/ravi/mt/montepython/mcmc.py", line 466, in chain
    Cholesky, Rotation) is True:
  File "/home/ravi/mt/montepython/mcmc.py", line 193, in get_new_position
    data.update_cosmo_arguments()
  File "/home/ravi/mt/montepython/data.py", line 908, in update_cosmo_arguments
    m_s_eff = self.cosmo_arguments[elem]/self.cosmo_arguments['deg_ncdm__2']
KeyError: 'deg_ncdm__2'

Regards 
Ravi kumar sharma

**Comment by brinckmann** [comment]
Aha, gotcha. You need to define the two species separately, i.e. please add
```
data.cosmo_arguments['deg_ncdm__1'] = 3
data.cosmo_arguments['deg_ncdm__2'] = 1
```
instead of
`data.cosmo_arguments['deg_ncdm'] ='3,1'`

You will also need to set the mass of the first species via `'m_ncdm'`, either by fixing it with 
`data.cosmo_arguments['m_ncdm'] = 0.06`
Or varying it the usual way.

Best,
Thejs

**Comment by brinckmann** [comment]
Note that
`data.cosmo_arguments['m_ncdm'] = 0.06`
sets the total mass of the active neutrinos to 0.18 eV, with 'm_s_eff' giving the effective mass of the sterile neutrinos.

Best,
Thejs

**Comment by ravi398** [comment]
thank you for your quik reply.
i set as follows
data.parameters['m_s_eff'] = [ 3, 0, 10, 0.5, 1, 'cosmo']
data.cosmo_arguments['N_ur'] = 0.00641
data.cosmo_arguments['N_ncdm'] = 2
data.cosmo_arguments['m_ncdm'] = 0.06
data.cosmo_arguments['T_ncdm'] = '0.71611,4.23418'
data.cosmo_arguments['deg_ncdm__1'] =3
data.cosmo_arguments['deg_ncdm__2'] =1

but this gives another error about

Cosmological Module Error:
 /|\   Something went wrong when calling CLASS
/_o_\  Error in Class: Class did not read input parameter(s): deg_ncdm__2,
       deg_ncdm__1


Regards
Ravi kumar sharma





now its giving enother error

**Comment by brinckmann** [comment]
I see. Sorry about that! It would seem I didn't code m_s_eff to work without deg_ncdm as a cosmo parameter. There are a few ways to get around this. One is to specify deg_ncdm__1 and deg_ncdm__2 as a cosmo parameter that you don't allow to vary:
```
data.parameters['deg_ncdm__1'] = [ 3, 3, 3, 0., 1, 'cosmo']
data.parameters['deg_ncdm__2'] = [ 1, 1, 1, 0., 1, 'cosmo']
```
This should let the code pick up the parameters and rename them correctly before passing them to class (it doesn't do this with cosmo arguments, only cosmo parameters, I forgot).

However, since the second species has deg_ncdm__2 = 1 using m_ncdm__2 and m_s_eff is equivalent (since m_s_eff just sets m_ncdm__2 = m_s_eff/deg_ncdm__2. So you could also try the following:
Set as a cosmo parameter m_ncdm__1 (not varied) and m_ncdm__2:
`data.parameters['m_ncdm__1'] = [ 0.06, 0.06, 0.06, 0., 1, 'cosmo']`
`data.parameters['m_ncdm__2'] = [ 3, 0, 10, 0.5, 1, 'cosmo']`
where you had to fix m_ncdm__1 in the same way as deg_ncdm_1 above in order to get the parameters renamed correctly for class.While setting deg_ncdm as a list:
`data.cosmo_arguments['deg_ncdm'] ='3,1'`

The two approaches should both work and are equivalent in your case, but _only_ for deg_ncdm__1=1 ! Otherwise you have to use the first approach.

Also note that if you're changing assumptions about the particle physics model neither approach may be correct. Specifically, it assumes it is Dodelson-Widrow-like production mechanism for the sterile neutrino. See paragraph 3 of section 7.5.3 of the [Planck 2018 paper](https://arxiv.org/abs/1807.06209). If you have e.g. a thermal sterile neutrino the effective mass to actual mass conversion is different. This is an easy change to make in montepython/data.py where all you have to change is the part for m_s_eff where it converts m_s_eff to m_ncdm.

Best,
Thejs

**Comment by ravi398** [comment]
it worked ...thank you very much
regards
Ravi
