### ISSUE TITLE
reason behind one or two parameters not converging ?

### ISSUE THREAD

**Issue by ravi398** [brinckmann/montepython_public#162]
Hello
I am varying sterile neutrino mass(with nonthermal distribution) as using Planck data sets
data.parameters['m_ncdm__1']  = [0.01,     0, 0.1, 0.01,     1,   'cosmo']
data.parameters['m_ncdm__2']  = [3,     0, 10, 0.5,     1,   'cosmo']

but convergence of m_ncdm_2 is very bad while  convergence of m_ncdm__1 is good.other parameters also converging.
what might be reason behind this? how does setting inerval or 1 sigma width or scaling play a role?
i am getting bestfit of m_ncdm__2 is  3.077 but with R-1=2.6 
please  Help me to understand this?

Thank you
Regards
Ravi kumar sharma

**Comment by brinckmann** [comment]
Hi Ravi,

Are you also varying the degeneracy of each species, or is that fixed? If you're also varying deg_ncdm__2 you will need a prior on the pass, probably on the effective mass (e.g. m_s_eff) so that you avoid the part of parameter space where deg_ncdm__2 can be arbitrarily small and m_ncdm__2 arbitrarily large.

If deg_ncdm__2 is fixed it's likely a covariance matrix or sigma issue, i.e. the starting guess or covmat was poor. This is a common problem and can take some tweaking to get around. By default, MontePython will start updating the covmat at max(R-1) < 3. However, it will only use the last 50% of the chain to make the estimate more current, so even though your max(R-1)=2.6, when only using the last 50% of the chains it may not have reached that. So what can happen is if your starting guess is sufficiently poor the code may never reach that point. It looks like your run is almost there. Honestly, R-1 < 3 is somewhat arbitrarily chosen, as is the 50% of the steps cut-off. At any point you can force the code to compute a new covmat and if --update is enabled (it is by default) it will load the new covmat as normal.

You do this by analyzing the chains with the `--want-covmat` flag:
`python montepython/MontePython.py info chains/your_run/ --want-covmat --keep-fraction 0.8 --keep-non-markovian --noplot --minimal`
where I set it to keep 80% to have a slightly larger sample. The code is likely to update your covmat again in the near future after doing this, so any choices made here shouldn't have a huge impact. Keep in mind that once you compute a covmat everything before that is "non-Markovian" and to be perfectly consistent should not be included in the final analysis. By default, MontePython will remove all non-Markovian points and so your R-1 values will jump by a lot, but will quickly decrease as you now have a much better covmat to sample the posterior. You can always check the full sample by including the flag `--keep-non-markovian` .

Best,
Thejs

**Comment by ravi398** [comment]
Thank you very much.


also i am not able to use covariance matrix on my cluster on any run it gives some error like 


OMP: Error #15: Initializing libiomp5.so, but found libiomp5.so already initialized.
OMP: Hint: This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
Aborted (core dumped)


this problem is there even for single chain with 10 points,without -c covmat/output.covmat options things are fine.
please help me through this .

regards
Ravi kumar sharma

**Comment by brinckmann** [comment]
I'm sorry, that's a cluster/software issue you will have to work out and one that I probably can't help with. Getting Metropolis-Hastings MCMC runs to converge without a covmat will often be extremely challenging. You could try to use different samplers such as emcee via cosmohammer or multinest, but those have their own problems.

Best,
Thejs
