### ISSUE TITLE
Hi all, Could you please tell me how to plot 3sigma contour in 2D plot using info?

### ISSUE THREAD

**Issue by nkhadka21** [brinckmann/montepython_public#165]

**Comment by dchooper** [comment]
Hi,

By default MontePython only plots the 1- and 2-sigma contours: to my knowledge, this is currently not something you can request in an additional plot file.

In order to get the 3-sigma contour, you can modify the analyze.py file: around line 885 there's a comment explaining why only 1- and 2- sigma are plotted, so that section is where you would need to make your changes.

Hope this helps!
Best,
Deanna
