### ISSUE TITLE
problem  running montepython with python-2.7.5

### ISSUE THREAD

**Issue by ravi398** [brinckmann/montepython_public#172]
Dear Sir
i have installed planck 2018,class_public-2.9.4 and running montepython with python-2.7.5 but when i run montepython it stucks after few lines..

Running Monte Python v3.3.4

with CLASS v2.9.0

Testing likelihoods for:
 ->Planck_highl_TTTEEE, Planck_lowl_EE, Planck_lowl_TT

----
clik version 3be036bbb4f9
  smica
Checking likelihood '/home/ravi/code/plc_3.0/plc-3.01/../../../baseline/plc_3.0/hi_l/plik/plik_rd12_HM_v22b_TTTEEE.clik' on test data. got -1172.47 expected -1172.47 (diff -4.34053e-07)
----
Initializing SimAll
----
clik version 3be036bbb4f9
  simall simall_EE_BB_TE
Checking likelihood '/home/ravi/code/plc_3.0/plc-3.01/../../../baseline/plc_3.0/low_l/simall/simall_100x143_offlike5_EE_Aplanck_B.clik' on test data. got -197.99 expected -197.99 (diff -4.1778e-08)
----
----
clik version 3be036bbb4f9
  gibbs_gauss b13c8fda-1837-41b5-ae2d-78d6b723fcf1
Checking likelihood '/home/ravi/code/plc_3.0/plc-3.01/../../../baseline/plc_3.0/low_l/commander/commander_dx12_v3_2_29.clik' on test data. got -11.6257 expected -11.6257 (diff -1.07424e-09)
----

after these line it stuck here.

may you please help me regarding this.

thanking you.

regards
ravi kumar sharma

**Comment by ravi398** [comment]
this problem persists with python-3.6.3 also. all the modules are  1) prun/1.3   2) intel/2019   3) impi/2019   4) ohpc   5) python/3.6.3   6) gnu7/7.3.0
 @brinckmann sir, may you help ? is its known comman problem ?


Regards
Ravi kumar sharma

**Comment by brinckmann** [comment]
Can you try to do some work to identify where the problem might be? It might be that the Planck installation or dependencies are faulty and need to be reinstalled. A few things you can try:
* Run with a Planck cosmology bestfit file with `-b bestfit/base2018TTTEEE.bestfit` and force it to make no jump with `-f 0`. 
* This will tell us if a likelihood was getting held up due to sampling outside of the allowed parameter range for the likelihood. If this works you may want to reexamine what you were doing before in terms of the cosmology you were sampling. Was it outside normal parameter ranges? Is it a special model you implemented yourself in CLASS or a standard CLASS version?
* Try to run without any Planck likelihoods (e.g. with fake_planck_realistic instead) and then gradually add in the Planck likelihoods one by one. Keep using the -b and -f flags above, we just need the code to compute one data point to see if it works at all.
* The first part will tell us if CLASS + MontePython is running properly at all, irrespective of Planck. The second part if there's a problem with a specific Planck likelihood. It seemed like it stopped during or after checking the Commander Planck_lowl_TT likelihood. If it was after, the problem may lie somewhere else.

Best,
Thejs

**Comment by ravi398** [comment]
Thank  you sir for reply.

1.The problem continue when i run with -b bestfit/base2018TTTEEE.bestfit evem with simple class with -f 0.
2. the problem aslo continue with fake planck data . it stops after following steps

Running Monte Python v3.3.4

with CLASS v2.9.4

Testing likelihoods for:
 ->fake_planck_bluebook

Initialised likelihood_mock_cmb with following options:
  unlensed_clTTTEEE is False
  Bmodes is False
  delensing is False
  LensingExtraction is False
  neglect_TD is True
  ExcludeTTTEEE is False
  OnlyTT is False

after this MP stops.

regards 
Ravi kumar sharma

**Comment by brinckmann** [comment]
Thanks! Can you check that your class installation works and that you can run it through the python wrapper?

Best,
Thejs

**Comment by ravi398** [comment]
Hello sir
when I compile class it doesnot show any errors. 
i run following scripts and run sucessfully 
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as sp
from classy import Class

my_model = Class()
my_model.set({'omega_b':0.022032,'omega_cdm':0.12038,'h':0.67556,'A_s':2.215e-9,'n_s':0.9619,'tau_reio':0.0925})
my_model.set({'output':'tCl,pCl,lCl,mPk','lensing':'yes','P_k_max_1/Mpc':3.0})
my_model.compute()

thank you
regards
Ravi sharma

**Comment by brinckmann** [comment]
It's possible you have a python version problem since you mentioned using two different python versions. MontePython should be run with the same version of python that you used when compiling CLASS and the wrapper. Can you check that this is the case (perhaps recompiling CLASS is the simplest)?

Best,
Thejs

**Comment by ravi398** [comment]
yes sir . i have compiled class under same version which i am using to run montepython. and class does not show any error.

thanking you
regards
ravi kumar sharma

**Comment by ravi398** [comment]
hello sir
I am still not figure out this problem.i have used same version of python for class and MP.  but problem still perisists.

@brinckmann  sir please help.

thanking you
regards
Ravi sharma

**Comment by dchooper** [comment]
Hi Ravi,

Could you specify a bit more the behaviour you are getting with MP? When you say "it stops", does it produce an error message, or just stop printing stuff to the screen? 

Best,
Deanna

**Comment by ravi398** [comment]
Hi
just stop printing stuff to the screen.

REgards
Ravi sharma

**Comment by dchooper** [comment]
Hi,

How long does MontePython stay in this frozen state? Have you tried leaving it for a longer period of time? This seems to be specific to the environment in which you are running, as this problem does not seem to occur elsewhere. Did you modify MP in any way?

Best,
Deanna
