### ISSUE TITLE
What is pk_cb?

### ISSUE THREAD

**Issue by ivandebono** [brinckmann/montepython_public#2]
I'm trying to run Montepython 3 for the Euclid_pk likelihood, which uses the parameter cosmo.pk_cb. This is not defined in CLASS, so I'm obviously getting an error:
AttributeError: 'classy.Class' object has no attribute 'pk_cb'

Is this a bug? Should it just be cosmo.pk, as in the previous version of the code? Or is the likelihood file written for some other version of CLASS, not publicly released?

**Comment by brinckmann** [comment]
Hi Ivan,
I accidentally pushed the wrong Euclid likelihood for the last release. The one you were trying to use requires features that are not yet publicly available in CLASS and has not been properly prepared for release. Since we're still working on the likelihood and on the new CLASS version, I suggest instead using the likelihood employed by Audren et al 1210.2194, with updated numbers for the Euclid mission in 2016, which I have now restored on version 3.0. The final likelihood and CLASS version will probably be available in a month or so, but is any case based on the Audren likelihood.
Best,
Thejs
