### ISSUE TITLE
Using Planck likelihoods

### ISSUE THREAD

**Issue by mahtaparsa** [brinckmann/montepython_public#208]
In order to use Planck likelihoods (for example "Planck_lowl_BB", "Planck_lensing", "Planck_highl_TTTEEE", ...) should one change the following lines in input.c module to "_TRUE_"? 
  ppt->has_cl_cmb_temperature = _FALSE_;
  ppt->has_cl_cmb_polarization = _FALSE_;
  ppt->has_cl_cmb_lensing_potential = _FALSE_;
  ppt->has_cl_number_count = _FALSE_;
  ppt->has_cl_lensing_potential = _FALSE_;
  ppt->has_pk_matter = _FALSE_;
  ppt->has_density_transfers = _FALSE_;
  ppt->has_velocity_transfers = _FALSE_;
  ppt->has_metricpotential_transfers = _FALSE_;

  ple->has_lensed_cls = _FALSE_;

  if (compute_sigma8 == _TRUE_) {
    pt.k_max_for_pk=10.0; // increased in June 2020 for higher accuracy
    pt.has_pk_matter=_TRUE_;
    pt.has_perturbations = _TRUE_;
    pt.has_cl_cmb_temperature = _FALSE_;
    pt.has_cls = _FALSE_;
    pt.has_cl_cmb_polarization = _FALSE_;
    pt.has_cl_cmb_lensing_potential = _FALSE_;
    pt.has_cl_number_count = _FALSE_;
    pt.has_cl_lensing_potential=_FALSE_;
    pt.has_density_transfers=_FALSE_;
    pt.has_velocity_transfers=_FALSE_;
    nl.has_pk_eq=_FALSE_; // not needed since sigma8 is derived from linear P(k)
    nl.method=nl_none;    // not needed since sigma8 is derived from linear P(k)
  }
because the default is "_FALSE_" in the CLASS code.
Thanks

**Comment by dchooper** [comment]
Hi,
You do not need to modify the CLASS code in any way to run the Planck likelihoods. To run with Planck, make sure you have installed the likelihoods (see instructions https://github.com/brinckmann/montepython_public#the-planck-likelihood-part), and then you can run with e.g.
`python montepython/MontePython.py run -p input/base2018TTTEEE.param -o chains/test -N 10`

If you are having a specific issue running, do let us know what the problem is so we can help further.

As a note, the lines you quoted from CLASS are all set to FALSE because this is purely where the default settings are declared. These are overwritten automatically by CLASS depending on what the user requests (for example, if you request tCl in your output, all of the relevant `has_cl_x` flags will change to TRUE).

Best,
Deanna

**Comment by mahtaparsa** [comment]
Thank you so much.
