### ISSUE TITLE
Problem with dark energy with JLA data

### ISSUE THREAD

**Issue by am610** [brinckmann/montepython_public#212]
Using JLA_simple data, where my params look like this, I am getting errors shown below
```
# Cosmological parameters list
data.parameters['omega_cdm'] = [0.2562, None,None, 0.008,1, 'cosmo']
data.parameters['w0_fld'] =  [-0.92, -5, 0.333, 0.008, 1, 'cosmo'] #-0.92
data.parameters['wa_fld'] =  [0., None, None, 0.008, 1, 'cosmo'] # 0.12

# Nuisance
#data.parameters['alpha']   = [0.15 ,  None, None, 0.001, 1, 'nuisance']
#data.parameters['beta']    = [3.559,  None, None, 0.02,  1, 'nuisance']
data.parameters['M']       =  [-19.02, None, None, 0.004,  1, 'nuisance']
#data.parameters['Delta_M'] = [-0.10,  None, None, 0.004,  1, 'nuisance']

# Derived parameter list
data.parameters['Omega_m'] =    [0.,    -1, -1, 0,1,  'derived']
data.parameters['Omega0_fld'] = [0.,    -1, -1, 0,1,  'derived']

data.cosmo_arguments['Omega_Lambda'] = 0
```
Errors are typically like this :
```
-> Scanning file output/jla_simple/2021-05-27_1000__1.txt: Removed 49 points of burn-in, and first 50 percent, keep 1 steps
Step  190  chain  0 : Failed to calculate covariance matrix


Error in Class: background_init(L:784) :error in background_solve(ppr,pba);
=>background_solve(L:1893) :error in generic_evolver(background_derivs, loga_ini, loga_final, pvecback_integration, used_in_output, pba->bi_size, &bpaw, ppr->tol_background_integration, ppr->smallest_allowed_variation, background_timescale, ppr->background_integration_stepsize, pba->loga_table, pba->bt_size, background_sources, ((void *)0), pba->error_message);
=>evolver_ndf15(L:499) :condition (absh <= hmin) is true; Step size too small: step:5.15779e-14, minimum:5.15779e-14, in interval: [-32.2362:0]
```

**Comment by brinckmann** [comment]
You should put some prior bounds on wa_fld and tighter bounds on w0_fld. I usually don't go below w0_fld < -3 or -3.5 and I sample the parameter "w0wa" (along with w0_fld), which is w0_fld + wa_fld. MontePython then takes the value from w0_fld and computes wa_fld from w0wa, passing w0_fld and wa_fld to class. The key here is this allows you to place a prior range on w0_fld + wa_fld instead of only on wa_fld.

Here's what I used in my last run:
data.parameters['w0_fld']       = [     -1.,    -3., -0.3334,     0.2,    1, 'cosmo']
data.parameters['w0wa']         = [     -1.,    -4.,   0.,        0.2,    1, 'cosmo']

Best,
Thejs

**Comment by shan1525** [comment]
Hi @am610 , 

One more thing to ponder besides what @brinckmann has suggested. I think you have written the priors for Omega_cdm not omega_cdm in the cosmological parameters list. 

Best, 
Shan.

**Comment by am610** [comment]
Ok thanks. @shan1525  yes thanks for pointing. solved.

**Comment by am610** [comment]
ok

**Comment by am610** [comment]
Hi,
I would like to ask this question (maybe naive) that if I run with a param file like you suggested, i.e. using `w_0 `and `w_0w_a`. How would I plot a `w_0-w_a` ?
thanks

**Comment by brinckmann** [comment]
Have a look at the example plot file plot_files/example.plot , this has examples for changing or adding parameters.

Since w0wa is just w0_fld + wa_fld it is easy to add a new parameter wa_fld computed from old ones
`info.to_derive = {'w_a': 'w0wa-w0_fld'}`
while optionally also renaming w0_fld
`info.to_change = {'w0_fld': 'w_0'}`

OR you can redefine the existing parameter
`info.redefine = {'w0wa': 'w0wa-w0_fld'}`
plus change the parameter name via
`info.to_change = {'w0wa': 'w_a', 'w0_fld': 'w_0'}`

The two approaches should be equivalent, except the former will leave the dummy parameter 'w0wa' in your parameter list. You could get rid of this by specifying which parameters to plot with the `info.to_plot` line of the example file. With `info.to_plot` you need to specify names exactly as in the log.param unless you specified new names with `info.to_change` or `info.to_derive`.

In either case, your parameters will be named w_a and w_0 if you include `info.to_change` as above. You don't need to rename the parameters, I just thought you might want to. 

Best,
thejs

**Comment by am610** [comment]
ok thanks. What if I  want to take the chains and plot them in getdist ?

**Comment by Rockdeldiablo** [comment]
> You should put some prior bounds on wa_fld and tighter bounds on w0_fld. I usually don't go below w0_fld < -3 or -3.5 and I sample the parameter "w0wa" (along with w0_fld), which is w0_fld + wa_fld. MontePython then takes the value from w0_fld and computes wa_fld from w0wa, passing w0_fld and wa_fld to class. The key here is this allows you to place a prior range on w0_fld + wa_fld instead of only on wa_fld.
> 
> Here's what I used in my last run: data.parameters['w0_fld'] = [ -1., -3., -0.3334, 0.2, 1, 'cosmo'] data.parameters['w0wa'] = [ -1., -4., 0., 0.2, 1, 'cosmo']
> 
> Best, Thejs

Hi Dr.   @brinckmann , i am an undergraduate student trying to do the same thing but i get the message

` /!\ could not derive minimum credible intervals for this multimodal posterior
 /!\ please try running longer chains or reducing the number of bins with --bins
     BINS (default: 20)

` 
with these settings (60k steps with superupdate option enabled)

`data.experiments=['JLA_simple']


# Cosmological parameters list
data.parameters['Omega_cdm'] = [0.2562,  None, None, 0.008,  1, 'cosmo']
data.parameters['w0_fld'] = [ -1., -3., -0.3334, 0.2, 1, 'cosmo']
data.parameters['w0wa'] = [ -1., -4., 0., 0.2, 1, 'cosmo']
# Nuisance

data.parameters['M']       = [-19.02, None, None, 0.004,  1, 'nuisance']


# Derived parameter list
data.parameters['Omega_m'] = [0,    -1, -1, 0,1,  'derived']


data.cosmo_arguments['Omega_Lambda'] = 0
 
#data.cosmo_arguments['fluid_equation_of_state'] = 'CLP'`

i was wondering how many steps are usually required to get good plots?
