### ISSUE TITLE
The .clik file for the likelihood Planck_highl_TE can not be found

### ISSUE THREAD

**Issue by PhyPy-Dm** [brinckmann/montepython_public#216]
Hi everyone,

 I write the likellihood of Planck_highl_TE, whose data is not included in baseline data, I download the data folder and configure its path, but there is an error as the following:
```
Likelihood Error:
 /|\   The path to the .clik file for the likelihood Planck_highl_TE was not
/_o_\  found where indicated:
       /home/hejiayin/MCMClass/baseline/plc_3.0/hi_l/plik/plik_dx11dr2_HM_v18_TE
       .clik
```
Well, you see the .clik is in the path but can not be found.
And I've check the data path again, it's the right path, I don't know what case the problem. And by the way, I also download the Planck 2015 data, and configure it's path, and when running program I meet the same errors. Is there anyone know how to fix the problem?

Best
PhyPy-Dm

**Comment by arsalanadil** [comment]
Update: It seems to me that this is not a MP issue, but one that stems from clik. It appears that clik does not like to be instantiated more than once. I was using both Panck_highl_TT and Planck_highl_TE and if you switch the order of the two in the .param file passed to MP, it will always stumble on the second of the two.  
As a check that this issue originates in clik,  in a python terminal one can try:
`
import clik` 
`clik.clik(/path/to/TE.clik)`
`clik.clik(/path/to/TT.clik)`

The first one should work fine, while the second one returns a `clik.lkl.CError`. Maybe this is on purpose due to some covariances between the two and so the authors of clik were clever to prevent people from using the two likelihoods in this way? I am not sure; but would be happy to hear from anyone if they have previously encountered and solved this issue.

Thanks!
Arsalan
