### ISSUE TITLE
Not computing covariance matrix , --update Issue

### ISSUE THREAD

**Issue by lanny222** [brinckmann/montepython_public#23]
using --update 500, does not produce the covariance matrix for me? any help?

mpirun -np 8 python MontePython.py run -o ../chains/fT1_convergenceTest -p ../sN1a_plc_Bao.param --update 500 -N 750000 --conf ../default.conf -f 1.5

--> Scanning file ../chains/fT1_convergenceTest/2018-11-17_750000__1.txt : Removed 314 points of burn-in, and first 50 percent, keep 1372 steps
2018-11-17_750000__2.txt1 342.104 1.216262e-01 -2.458553e-03 1.396239e-01 3.125691e+00 -1.911299e+01 -7.420085e-02 3.113078e-01 6.800000e+01 0.000000e+00
1 344.931 1.129606e-01 -5.812980e-02 1.503880e-01 3.198529e+00 -1.908845e+01 -7.028718e-02 2.925674e-01 6.800000e+01 0.000000e+00
: Removed 129 points of burn-in, and first 50 percent, keep 1702 steps
2018-11-17_750000__3.txt : Removed everything: chain not converged
2018-11-17_750000__4.txt : Removed everything: chain not converged
2018-11-17_750000__5.txt : Removed 72 points of burn-in, and first 50 percent, keep 2277 steps
2018-11-17_750000__6.txt1 350.949 1.354452e-01 1.616572e-01 1.568599e-01 3.272936e+00 -1.904745e+01 -8.283017e-02 3.411933e-01 6.800000e+01 0.000000e+00
: Removed 70 points of burn-in, and first 50 percent, keep 2221 steps
2018-11-17_750000__7.txt : Removed everything: chain not converged
2018-11-17_750000__8.txt : Removed everything: chain not converged
--> Computing mean values
--> Computing variance
--> Computing convergence criterium (Gelman-Rubin)
-> R-1 is 0.006293 for omega_cdm
0.035296 for b
0.005224 for alpha
0.009577 for beta
0.005479 for M
0.017239 for Delta_M
0.006294 for Omega_m
0.006294 for H0
0.006295 for sigma8
--> Not computing covariance matrix

**Comment by brinckmann** [comment]
Hi,
The code is designed to stop automatically updating the covariance matrix after some time, in order to allow the chains to converge once a good enough covmat has been obtained. This stopping point is set (a bit arbitrarily) to max(R-1)=0.3. Usually this is good enough to obtain the desired convergence.

However, occasionally, your input covmat will be good enough for your chains to obtain some level of convergence, but not good enough to obtain the desired level. In these cases you can manually compute a covariance matrix with e.g. `python MontePython.py info ../chains/fT1_convergenceTest --want-covmat`

This is fine to do during an on-going run. The code will detect the new covmat and proceed with that one instead. Note that, of course, this will increase the number of non-markovian points removed by default during an analysis, so the convergence will initially be worse if you analyze the chains.

Also, if you're using MontePython v3, setting --update to 500 is a very large number (this would have been reasonable in the past, but now the input value is rescaled by the number of steps per cycle) and I would instead recommend something like 50.
Best,
Thejs

**Comment by lanny222** [comment]
Cheer Thejs, the problem at the moment is that im trying to run planck 2015 in conjunction with wiggleZ_bao and JLA, but some of the paramaters' R-1 value is sufficiently small whilst others are blowing up, so im inclined to thinking that this is due to the covariance matrix not being computed.

Also i am using --update 500 because ive read that when using planck in conjunction with anything else an update of 300-1000 should be used but if you think smaller is better then i will give it a shot.

Thanks for the help.

Alain.

**Comment by lanny222** [comment]
@brinckmann any suggestions on how i can try and work around or fix issues when the R-1 value of certain parameters blow up relative to the rest?

**Comment by lanny222** [comment]
@brinckmann Working perfectly now, realised problem of non converging parameters using these likelihoods was because i was still using an outdated version of montepython. Thank you for the help
