### ISSUE TITLE
Run time error : Fatal error in PMPI_Init_thread: Other MPI error, error stack:

### ISSUE THREAD

**Issue by am610** [brinckmann/montepython_public#238]
I have seen #19 but it is not clear to me what exactly is the proposed solution to this error ? I am setting up montepython in Nersc machine, as a workaround, I had tried this  solution,

`import mpi4py.rc         
  mpi4py.rc.initialize = False`
But no success...
So can you suggest any working solution ?

**Comment by brinckmann** [comment]
Hi,

I don't use NERSC myself, but asked around and got what I think is a useful answer:

Those error messages occur because MPI doesn't work on the login nodes on NERSC. At least, that's the only time I've seen it.

In general, users need to either submit a job to the compute nodes (the "regular" queue on NERSC; good for running chains), or request an interactive job session on one of the computing nodes (good for quick testing). NERSC has some pretty good documentation here: https://docs.nersc.gov/jobs/

Good luck!
Thejs
