### ISSUE TITLE
Method to deal with low acceptance rate with Planck 2018 data

### ISSUE THREAD

**Issue by EFrion** [brinckmann/montepython_public#251]
Hi guys,

I am trying to constrain a model consisting of LCDM + 3 free parameters using the Planck 2018 TTTEEE data. With the command
> mpirun -np 4 python3 montepython/MontePython.py run -p input/sde_planck.param -o chains/sde_planck --superupdate 20 -N 100

I have no problems finding posteriors with good acceptance rate for other experiments (e.g. JLA), but I get very low acceptance rate with Planck. Following the discussion in issue [#53](https://github.com/brinckmann/montepython_public/issues/53), I have tried the following method:

1. Run an initial chain in the directory sde_planck2 with the option -f 0.5 (acceptance rate: 0.3<AR<0.5)
> mpirun -np 4 python3 montepython/MontePython.py run -p input/sde_planck.param -o chains/sde_planck2 -f 0.5 -N 250
2. Compute the covariant matrix
> python3 montepython/MontePython.py info chains/sde_planck2/ --extra plot_files/sde_planck.plot --want-covmat
3. Do a quick test run in a new folder sde_planck using this matrix. The output gives an acceptance rate between 0.4 and 0.6, which is much better in my understanding, since I would only run longer chains afterwards to bring it around 0.25.
> mpirun -np 4 python3 montepython/MontePython.py run -p input/sde_planck.param -o chains/sde_planck -c chains/sde_planck2/sde_planck2.covmat --superupdate 20 -N 25
4. And now I try with a longer chain, restarting from the previous short chains.
> mpirun -np 4 python3 montepython/MontePython.py run -r chains/sde_planck/2021-12-13_100__1.txt -o chains/sde_planck -c chains/sde_planck2/sde_planck2.covmat --superupdate 20 -N 5000
5. Keep restarting the chains until I am satisfied with the convergence criteria

However, I am in doubt whether this is the way to go or not. Does this method make sense? Since I am using the superupdate option, I would have expected the covariance matrix to change along the run, but it does not. Can I actually use the -c and --superupdate options together? 

In general, what is your favourite method to use Planck data in your models?

Many thanks!
Manu

**Comment by lesgourg** [comment]
Hi @EFrion , I am surprised by your strategy, this is not at all the kind of things that we do - we do much simpler. Thus I would like to answer you in details, hoping that this could benefit also to other users.

In a problem like this, typically, we would start from the provided covmat `covmat/base2018TTTEEE.covmat`, which already contains all the correlations involving the 14 planck nuisance params + 6 LCDM params, and at the same time, from the best fit file `bestfit/base2018TTTEEE.bestfit` to avoid long burn in. For the input file,  I would modify `input/base2018TTTEEE.param` to add your 3 new parameters, with a sensible guess for the bestfit value (first number in the array) and the expected standard deviation (4th numbest in the array). The convergence time will depend on how good was the guess on these three new standard deviations, and how correlated are the 3 new parameters with each other and with the others. If you use also planck lensing and/or BAO, you ahve similar set of covmat, bestfit, input files named base2018TTTEEE_lensing or base2018TTTEEE_lensing_bao.

Then I would do a **single** run:

`mpirun -np 4 python3 montepython/MontePython.py run  -p input/xxx.param -o chains/xxx -c covmat/base2018TTTEEE.covmat -b bestfit/base2018TTTEEE.bestfit -f 1.9 --superupdate 20 -N 100000`

The superupdate option will do automatically the job of optimising both the covmat and the jumping step size, so you don't have to go through a complicated strategy, and you don't need to think about -f, which will be adapted in order to converge towards an ideal acceptance rate of 025. In the previous line, I passed `-f 1.9` as an initial value, because this is usually a good guess for Planck 2018, but since it will be adapted automatically, you could even drop this option. We recommend running the previous command on your MPI cluster with something like 4 to 16 chains, with the option OMP_NUM_THREADS set to 4 to 12, such that each chain - and thus each call of CLASS - is parallelised over 4 to 12 cores (the optimal choice often depends on the number of CPU per core on your cluster). These numbers are just suggestions. With less than 4 chains and 4 CPU per chain, the performances are not very good, while with numbers larger than above, the efficiency increases marginally. If you have e.g. 8 chains on 8 cores, which is what I would use by default, I would expect that you get your final results in about 12 hours, unless your new parameters have a very complicated posterior distribution.

To address your points more in details:
- your first step with` -N 100` was most probably pointless, if not counter-productive: the 100 points you get are probably pure burn-in. Burn-in is deceptive: it may have a relatively good acceptance rate, while the points are in reality very bad, and the resulting covmat is terrible.
- the idea of running the chains by small chunks of 5000 is sub-optimal: such short chains don't leave time for the code to develop its automatic updating strategies for the covmat and the step size. A single long run will always perform better. Above, I wrote `-N 100000`, but this is just a way to say "keep running as long as you can": in practise, you can monitor your chains in real time and stop them when you are satisfied with the convergence ciriterium R-1. Maybe this will occur already after 10000 tries... In any case, the typical convergence time scale with 8 chains on 8 cores is 6 to 20 hours, depending on the complexity of the posterior for the new parameters, and on your guess for the 3 sigmas of the new parameters.
- I confirm that there is no problem in running with `-c` and `--superupdate` together, this is the normal thing to do.

The update of the covariance matrix will only start after a while, when max(R-1) becomes decent, and stop after a longer while, once max(R-1) becomes very good. When you will analyse your long chains, MP will keep by default only the Markovian points, that is, only the part of the chains that accumulated after the last update of the covariance matrix. This means that, while monitoring the run, you may have the impression that the plots are suddenly based on a very small number of points, smaller than a while ago: this just means that there was a recent covmat update. The ultimate goal is to let the code run one hour or two after the `last` update, in order to get enough markovian points in your plot. Actually, you can always cheat a bit and analyse the run with the option `--non-markovian`, in order to force all the points in the chains (excepted burn-in) to be taken into account in the plots. Then, the plots usually look nicer, because they are based on many more points. Throwing away the non-markovian points (which is the default) should only be seen as a way to get more exact results once a run is very well converged.

I hope this help!

**Comment by brinckmann** [comment]
Thanks for the detailed explanation, Julien, that should be helpful for people who are new to MontePython! I should add a document with tips and best practices sometime and include all of this.

Just a minor correction, the flag to keep non-markovian points is `--keep-non-markovian` and as an added tip it is often good to use it with `--keep-fraction 0.8` where the 0.8 can reasonably be anything from 0.9 to 0.7. The former includes all of the chains except for the burn-in, while the latter removes the initial 10-30% of the chain (indeed the combination `--keep-non-markovian --keep-fraction 0.7` would mimic default GetDist behavior). Note we do recommend analyzing without these two flags, as that's the only way we can guarantee the chains are Markovian, but there can be reasons for deviating from this (and in _most_ cases either will be fine), either as a diagnostic or because the covmat changed very little at a late stage once the chains were close to converged.

If you're running on a cluster that doesn't allow long enough runs you can use the restart option `-r chains/xxx/date__1.txt` , replacing date with the date of your chains, in order to mimic doing a longer run (look in the chains directory for the name of the `__1.txt` file). This has been explained in detail elsewhere on the issues pages (make sure to also check closed issues), so I won't repeat it here.

Best,
Thejs

**Comment by EFrion** [comment]
Thanks for your answers, Julien, Thejs, that's really helpful.

I feared that passing the  `-f` or `-c` options would fix the jumping factor and covmat, so that `--superupdate` would not alter them in the end. I understand better now.

I still have one doubt after reading your answers. Since I am working on my laptop, I have only 4 CPUs available, which makes the whole process very long. For this reason, I thought I could do several runs on different days, and using the `-r` options to obtain longer chains, as Thejs mentioned (and explained in #17). But if I understand Julien's answer correctly, if I only add small chains in this way, the `--superupdate` option may never have enough time to intervene, and my chains may never converge (or they make take a very long time to do so). Is that correct?

**Comment by lesgourg** [comment]
> Since I am working on my laptop, I have only 4 CPUs available, which makes the whole process very long. 

Oups! Now I see the problem. I am very sorry to say this, but all MCMC codes for cosmology are actually designed for being ran on clusters, or at least on big machines with many more cores - especially when you use the Planck likelihood and all its nuisance parameters. On your laptop I am afraid that you will not get results even after 4 months. You should really get access to the cluster of your university. I would say that using 16 CPUs is a strict minimum, 32 is better, 64 is optimal, more is a luxury. Note that you can also switch to the likelihood called planck_lite which has only one nuisance parameters instead of 14. But I would not run on a laptop even in that case.

**Comment by am610** [comment]
found this post relevant, running Planck lite, still I dont obtain convergence , what could be wrong ? 

Didnot use Fisher or covmat or best fit (as I am not sure if the Lite's have those with them). Simply ran all combined SN + Plank Lite in a cluster, doesn't converge even after 72 hours. Any comments what should be looked at?

**Comment by brinckmann** [comment]
Hi Ayan,

You don't provide much information, so it's hard for me to guess at the problem.

Do you use the update method (i.e. `--update`, which is enabled by default for all recent versions of MontePython)? This method updates the covmat automatically, speeding up convergence. Without a starting covmat it's hard to get converged otherwise. It should be reasonable to start from one of the covmats in the covmat/ folder. There is one for Planck lite without lensing, but you can probably use one of the full Planck covmats too. It's usually better to have some starting covmat than none at all (unless it is very wrong), and if necessary the update method will change the covmat to something more suitable.

Just to check, how many chains and how many cores per chain? we usually recommend 4-16 chains with 4-16 cores per chain. Optimal setup depends on server architecture, but something like 8 chains running on 6 or 8 cores each is usually my default for ordinary runs.

But 72 hours is a lot for just Planck + SN (assuming it's a simple model/posterior, otherwise it doesn't have to be), so I suspect some problem. Check that your parameters are correctly ordered, in type they should always be 'cosmo' followed by 'nuisance' followed by 'derived'. Any deviation from this causes problems obtaining convergence.

Best,
Thejs
