### ISSUE TITLE
Sigma value

### ISSUE THREAD

**Issue by SafaeCosmology** [brinckmann/montepython_public#256]
Hello everyone, 
I'm trying to run my calculations with MontePython, using the 6 standard parameters plus a new parameter that characterizes my model, when the calculations are finished  I don't get the sigma value for my new parameter, but when I run _**info .... - keep-non-markovian  --keep-fraction 0.8 --bins 10**_ I get sigma, can my result be considered good?

**Comment by brinckmann** [comment]
Dear Safae,

It is a known bug in MontePython that it sometimes fails to compute credibility intervals when it should be able to, and that this can be fixed by changing the binning (typically to lower values) in the way that you did here, even though that should have no impact on the computation of credibility intervals. If your run is converged (ideally max(R-1) ~ 0.01 or less, or at least 0.02-0.03), and the numbers appear to make sense, then I would say they are reliable despite this workaround.

Best,
Thejs

**Comment by SafaeCosmology** [comment]
Thank you very much, sir.
