### ISSUE TITLE
Flat prior on derived parameters

### ISSUE THREAD

**Issue by LilleJohs** [brinckmann/montepython_public#268]
Hi,

I want to have flat priors on the derived parameter Omega_Lambda, so that Omega_Lambda>0. I thought I could just do this
`data.parameters['Omega_Lambda']    = [1, 0   , None,    0,     1,   'derived']`
where the first 0 is the lower bound.

That did not work and after reading the documentation, I am not sure if this is a bug or if the derived parameters do not support flat priors this way.

How do I add flat priors to derived parameters?

**Comment by brinckmann** [comment]
Hi,

As you already learned, MontePython ignores priors for the derived parameters. You'll have to add the condition yourself, this can be done in a variety of ways, see replies to issue #266 . If no CLASS errors outside of the allowed parameter space the easiest is to add a likelihood that improses the condition, returning a very large -loglkl value (e.g. 1e8) for rejected points or a 0 otherwise. If CLASS complains you instead have to follow the other instructions. You can access the parameter via `cosmo.Omega_Lambda()` .

Best,
Thejs

**Comment by LilleJohs** [comment]
Great, thank you so much!
