### ISSUE TITLE
how to turn off fisher matrix computation?

### ISSUE THREAD

**Issue by thewomanxh** [brinckmann/montepython_public#29]
Hi,  I noticed that when we run montepython, it will automatically calculate fisher matrix to accelerate computation speed, right? However, my likelihood seems couldn't do that, do I have some options to turn off it?
Thanks a lot!

**Comment by brinckmann** [comment]
Hi,
MontePython should not compute a fisher matrix when you run without the options to activate it. What is the command you use to launch the run and are you using the latest version of the code?
Best,
Thejs

**Comment by thewomanxh** [comment]
Yes, I use version 3.0.1, and my command is something very simple like: ' python montepython/MontePython.py run -p *** -o *** -N **", but I always get some outputs like "chain not converged"  and "Failed to calculate covariance matrix", I have to say my likelihood function may not be Gaussian, the values of each parameters always reach the low limit of the range which I set in .param files. And if I release the parameter space, it will be weirder, but also divergent. Do you have any idea how to deal with this situation?

**Comment by brinckmann** [comment]
That shouldn't be related to a fisher matrix computation, but rather that your chains are (possibly) not converged. I say possibly because there's a bug that will be corrected very soon which causes too much of chains to be removed by default, see issue #27 for more information. You can get around this by using e.g. flags `--keep-non-markovian --keep-fraction 0.7` when analyzing the chains.
Best,
Thejs
