### ISSUE TITLE
Big Bang Nucleosynthesis (BBN)

### ISSUE THREAD

**Issue by SafaeCosmology** [brinckmann/montepython_public#301]
Hello everyone, I have a question regarding BBN data, I want to know please the difference between **_bbn_** and _**bbn_omegab**_ Likelihood.
Thank you in advance.

**Comment by brinckmann** [comment]
Hi Safae,

@schoeneberg is the best person to answer this question. I give the answer I got from him previously, but tag him in case he has anything to add.

> This is a bit of a philosophy question. For most cases, eta_b is the more direct quantity relevant for BBN, but personally I am of the philosophy to let codes deal with the conversion instead of trying to do it ourselves, and thus simply using the bbn_omega_b likelihood.

Best,
Thejs

**Comment by schoeneberg** [comment]
Dear @SafaeCosmology ,

the "bbn" likelihood is based on the BBN parameter "eta_b = number abundance of baryons/number abundance of photons" instead of being based on the more well known "omega_b" like the "bbn_omegab" likelihood. Usually you will want to use the "bbn_omegab" likelihood, I would say.

I suggest we might unify at some point the likelihoods and make the underlying used parameter a new option, since this has indeed created a bit of confusion for many people.

Let me know if there's anything else,
Nils Sch.

**Comment by SafaeCosmology** [comment]
Thank you very much for your answer
