### ISSUE TITLE
How to set sensible priors for w0-wa

### ISSUE THREAD

**Issue by seshnadathur** [brinckmann/montepython_public#32]
Is there a way to set a sensible physical prior on the combination of w0 and wa? For example, ensuring that w0 + wa <= 0. 

I have set priors -3 < w0 < -0.3 and -2 < wa < 2 on the parameters individually, but since the 1-sigma bounds are quite weak from current data, this is not sufficient to stop the chains from wandering into unphysical regions of parameter space, such that 
`w_fld >= 1./3.`
or 
`w_fld_ini > 0`
When it gets here, Class rightly complains for many reasons, and sometimes the chains completely stall and are unable to get back to sensible regions.

I imagine this issue would be automatically handled if one used a good estimate of the covariance matrix for the proposal, as the correlation between parameters might stop them moving simultaneously in the wrong direction. But I need to get the chains to progress sufficiently to be able to estimate this covariance!

**Comment by brinckmann** [comment]
Hi,

This example is covered in appendix A.3 of the MontePython 3 paper [Brinckmann & Lesgourgues 1804.07261](https://arxiv.org/abs/1804.07261).

Best,
Thejs

**Comment by ivandebono** [comment]
I came up against the same problem, namely, how to sample the w0-wa plane in a cosmological model that uses the CPL parameterisation, with mock data (with fiducial values w0_fld=-1 and wa_fld=0).

Using w0_fld and w0wa (as suggested in Appendix A3) didn't seem to help. 

I tried a different strategy, which was to run MontePython with w0_fld and w0_fld, with --method Fisher and -N 1 (or some small number of points; it doesn't really matter), and once the Fisher matrix is output, use its inverse as my covariance matrix with the option -c fisher_inv.mat .

But whatever my choice of priors and standard deviations, the wa_fld row and column in the covariance matrix (and the Fisher matrix) are all zeros. Am I doing something wrong?

**Comment by brinckmann** [comment]
Hi Ivan,

The likelihood when using w0 and wa can be either non-Gaussian or highly degenerate between parameters depending on your combination of likelihoods, which means computing Fisher matrices doesn't work well. If you send me an email with your likelihood combination I may have a covmat from a comparable run that I can send you.

When you say the w0wa parameterization didn't help, do you mean with a Fisher run or an MCMC? You may not have set the parameter boundaries tight enough. I restrict w0_fld=[-3.0,0.333] and w0wa=[-5.0,0.0], which at least produces few enough errors from CLASS for an MCMC run to be viable.

You can also try to turn off the pk_equal method in CLASS, which at least in the past caused problems for parameter extraction (it has since been updated, so it may be fine now). This is controlled in line 2880 of input.c in CLASS v2.7, which you can try to change from
```
  if ((pnl->method == nl_halofit) && (pba->Omega0_fld != 0.) && (pba->wa_fld != 0.))
    pnl->has_pk_eq = _TRUE_;
```
to
```
  if ((pnl->method == nl_halofit) && (pba->Omega0_fld != 0.) && (pba->wa_fld != 0.))
    pnl->has_pk_eq = _FALSE_;
```

Best,
Thejs

**Comment by ivandebono** [comment]
My boundaries were even narrower.

On w0wa:
All my data sets are fiducial (i.e. calculated from the f value fiducial values in the param file). I used 
"--method Fisher" first in order to output a Fisher matrix and its inverse, which I then used as my covariance matrix for the MCMC run (with "-c inv_fisher.mat").

This didn't help the MCMC run. In hindsight, I shouldn't have used the Fisher matrix when it is clearly inappropriate.
