### ISSUE TITLE
KiDS-1000 posteriors of nuisance parameters. 

### ISSUE THREAD

**Issue by karimpsi22** [brinckmann/montepython_public#329]
Hello, 

I just want to report an issue that I found in KiDS-1000 likelihoods. 
By using CLASS I was trying to obtain the Fiducial analysis from Asgari et al. paper: [https://arxiv.org/pdf/2007.15633.pdf](https://arxiv.org/pdf/2007.15633.pdf). Moreover, I considered the priors from `K1K.param` file and the CorrelationFunctions module, however, when I compare my posteriors to their results I am getting several differences in the nuisance parameters. 

Firstly, I got an opposite sign in the D_z's posteriors if I directly change the sign of my Dz's chains then everything is consistent with their results. This also is happening in the others modules (BandPowers and COSEBIs).  
Secondly, in CorrelationFunction as it mentioned that delta_c is needed for this module. The prior provided in the input file might be wrong and is not the same reported in the Table 2 from the paper. My posterior of delta_c is inconsistent with KiDS-1000 results.

I am attaching 2 plots of CorrelationFunction comparison with KiDS-1000 results, the first in **teal** is my unaltered results and second in **red** I introduced a minus sign in my Dz's chains, so the Dz's posteriors are in agreement.

- Does anyone know why the Dz's output chains are having an opposite sign?

Regarding delta_c parameter issue I think it might be fixed if we consider the prior range from the paper which is delta_c = 0 ± 2.3×10−4. 
 
That's it all I want to share. 

Cheers,
Karim 

[unaltered_class_2PCF_vs_K1K_data.pdf](https://github.com/brinckmann/montepython_public/files/11655986/unaltered_class_2PCF_vs_K1K_data.pdf)

[altered_class_2PCF_vs_K1K_data.pdf](https://github.com/brinckmann/montepython_public/files/11656025/altered_class_2PCF_vs_K1K_data.pdf)

**Comment by brinckmann** [comment]
Hi Karim,

Thanks for the report. @BStoelzner any thoughts on this?

Best,
Thejs

**Comment by BStoelzner** [comment]
Hi Karim,

The reason for the opposite sign in the Dz posterior is that the cosmosis pipeline used in Asgari et al. defines delta_z= z_true - z_est while the MontePython likelihood uses delta_z= z_est - z_true (this definition was also used for example in https://arxiv.org/abs/1909.09632; see Table 3). So, internally everything should be handled correctly; you just need to be aware of the relative minus sign when making comparison plots. @brinckmann maybe it's worth putting at comment on this in the .param file and/or the readme.

Regarding the delta_c parameter: It has been a long time since I last ran the 2PCF likelihood (since our preferred summary statistics for KiDS are COSEBIs and BandPowers) and I don't remember the exact details. But you're right: the prior on this parameter should be a Gaussian centred at 0 ± 2.3×10−4, as reported in Asgari et al. I guess that the values in the .param file are some old ones that didn't get updated since we never used the 2PCF likelihood extensively (and it doesn't seem to have a big impact on the cosmological parameters). 

Thanks for letting us know!

Best,
Benjamin
