### ISSUE TITLE
data/windows

### ISSUE THREAD

**Issue by facutoscano** [brinckmann/montepython_public#344]
Hi everyone!
I'm trying to create a new SPT likelihood (using the existing one in Montepython) and I have noticed that if you use this experiment, you need to add a window file for each Cls bin. Could someone explain me the values of these files? I think they are related to the Cls of each bin and the covariance matrix, but an explanation would be helpful.
Thank you!

**Comment by brinckmann** [comment]
Hi,

These likelihoods predate my affiliation with the code, but you can probably track down the answer in montepython/likelihood_class.py if you search for "newdat" (line 400 onwards in the public version plus the preceding functions used in the likelihood). I believe the three extra files are contamination spectra modulated by the nuisance parameters, with the first column the Cls and the second column giving the contamination due to SZ, due to Poisson point sources, and due to clustered point sources.

Note that these likelihoods are very old and there are newer SPT likelihoods available, you can find them here courtesy of Anton Chudaykin, who translated the official likelihoods to MontePython:
https://github.com/ksardase/spt3g-montepython
https://github.com/ksardase/SPTPol-montepython

Best,
Thejs
