### ISSUE TITLE
./waf install

### ISSUE THREAD

**Issue by HelenLinElen** [brinckmann/montepython_public#365]
Dear team!
Greetings!

I need you kind assistance within waf installing part comand: ./waf install  (The Planck likelihood part).

I am getting error : 

![Untitled](https://github.com/brinckmann/montepython_public/assets/163308888/a5360d55-358e-49c9-beaa-1821281aba15)

When I copy cython there - I have error: 

![Untitled1](https://github.com/brinckmann/montepython_public/assets/163308888/709390c2-f46b-4645-9179-b3f8e42ae8f7)

Could you suggest a solution, please?

Thank you in advance.
Kind Regards.
Elen

**Comment by brinckmann** [comment]
Hi Elen,

We don't normally help with Planck issues, since it's an external module, but I suspect maybe you need to use sudo? It looks like you're running on a home system and newer OS versions have started protecting against reading/writing of programs (including terminals) to directories they aren't expected to need, as a way to guard against viruses etc. Downloads can be one of these protected directories.

Best,
Thejs

**Comment by HelenLinElen** [comment]
Dear Thejs,

Thank you for your kind assistance.

Best Regards.
Elen
