### ISSUE TITLE
Conversion of PolyChord output not possible

### ISSUE THREAD

**Issue by fkoehlin** [brinckmann/montepython_public#50]
Hi all,

I'm trying to convert PolyChord (PC) output to a standard Monte Python chain via:

`montepython info /path/to/run/PC/`

This yields the following error message:

```
Traceback (most recent call last):
  File "/.../montepython_public_v3/montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/.../montepython_public_v3/montepython/run.py", line 31, in run
    custom_command)
  File "/.../montepython_public_v3/montepython/run.py", line 190, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/.../montepython_public_v3/montepython/initialise.py", line 58, in initialise
    analyze(command_line)
  File "/.../montepython_public_v3/montepython/analyze.py", line 82, in analyze
    status = prepare(item, info)
  File "/.../montepython_public_v3/montepython/analyze.py", line 222, in prepare
    "is missing in the analyzed folder?")
io_mp.AnalyzeError:

Analyze Error:
 /|\   The log param file PC/log.param is missing in the analyzed folder?
```
But of course, the `log.param` file is one folder up in `path/to/run/`... and I'm also not sure why Monte Python would need that file to just convert the PC output to a standard Monte Python chain?!
 
If I remember correctly, this is also the error message I saw when trying to convert MultiNest output back in the day as described in issue #5 (although this issue was for v3.0.1 whereas the current one is for v3.1.0...).

Cheers,

Fabian

**Comment by fkoehlin** [comment]
Hmm, the conversion works flawlessly on my Mac (with a more-or-less up-to-date anaconda Python 2.7 environment) but still fails as described above on a RedHat Linux work station (with a fairly old Python 2.7 setup...)...
Maybe the bug is caused by some outdated packages?!

**Comment by flo1984** [comment]
Hi Fabian, 

I'm having exactly the same issue. Did you resolve it in the meanwhile?

Thanks, Florian

**Comment by brinckmann** [comment]
Hi Florian,

Try to analyze with and without a trailing slash in the path (I can't remember which is correct and I actually think Fabian fixed that particular bug, but it's worth trying). Also make sure you analyze the chains directory and not the PC or MN subdirectory (i.e. chains/test_run/ rather than chains/test_run/PC/). If the analysis is successful this will create new directories (it may create more than one if there are multiple modes) in the chains directory with a log.param file included. You should then analyze the new subdirectories separately.

Best,
Thejs

**Comment by flo1984** [comment]
Hi Thejs,

Thanks, it worked without the trailing slash.

Best wishes,
Florian
