### ISSUE TITLE
Differences in GetDist and MontePython chain analysis

### ISSUE THREAD

**Issue by ivandebono** [brinckmann/montepython_public#52]
What are the (main) differences between MontePython and GetDist in the methods used to analyse chains?

As an experiment, I tried to analyse the same chains using both, and I get different results. The bestfit values are different.

For some chains (where convergence is slow) where  MontePython gives NaN values for the sigma bounds for the difficult parameters, GetDist gives normal numeric values.

**Comment by brinckmann** [comment]
Hi Ivan,

There are a couple of differences. MontePython has the feature that it can remove the non-markovian part of the chains.

By default the code will remove everything since the last time the covmat was updated. As of `v3.1` this behavior is controlled through the flags `--keep-non-markovian`, which keeps everything, and `--keep-only-markovian`, which removes everything non-markovian, i.e. removes everything since the last time the jumping factor or covmat was removed. If you want to directly compare to GetDist you should run with flags `--keep-non-markovian` and `--keep-fraction 0.7`, where the latter will remove the first 30% of the chains.

Additionally, MontePython will use a burn-in removal criteria, removing the start of the chains where the -Delta loglkl > 3. This is hard-coded in `montepython/analyze.py` line 40: `LOG_LKL_CUTOFF = 3`. In some _rare_ cases it can be beneficial to modify this criteria as well, but in most cases the default settings should be sufficient.

Note that in any case the plots will look different by default as the two codes use different smoothing options. See Appendix C of [Brinckmann & Lesgourgues 1804.07261](https://arxiv.org/abs/1804.07261) for more details.

Best,
THejs

**Comment by ivandebono** [comment]
Thank you, Thejs.

What are the best chain analysis options to help MontePython output sigma values for all the parameters? I tried keeping non-Markovian points but it didn't help.

**Comment by brinckmann** [comment]
The best is to run the chains for longer until they properly converge, but you can also try to adjust the histogram binning with `--bins`, which sometimes helps you get some preliminary values while waiting.

**Comment by ivandebono** [comment]
That's exactly the problem. The chains seem to have converged.

The acceptance rate for all the chains (I have 8) is 0.25. For the parameters in question, I get R-1 values of 0.000773 and 0.002087.

**Comment by brinckmann** [comment]
How many chains do you have? The accuracy of the Gelman-Rubin convergence diagnostic is proportional to 1/Nchains and is therefore unreliable for a small number of chains. I usually run with 8 chains and recommend a minimum of 4. Does your posterior appear to be multimodal? Maybe you can email me the plots and I'll have a look.

**Comment by SuvedhaNaik** [comment]
Hello @ivandebono, @brinckmann ,

Could you please share any updates on this issue?

I'm also stuck with similar problems. 
Currently I have 8 chains of 7X10^5 steps each. R-1 for the parameters I'm interested in are 0.000216 and 0.000171. However, the posteriors are multimodal and uniform [
[Posterior.pdf](https://github.com/brinckmann/montepython_public/files/3976708/Posterior.pdf)
](url). Sigma values are not generated. I'm running with flags   `--update 50 --superupdate 20` using Metropolis-Hastings sampling then analyzing with the flags `--keep-non-markovian --keep-fraction 0.7 --want-covmat`

How long should I go? or any other algorithms can be used to resolve this issue?
Any suggestions would be of great help. 

Thanks in advance, 
Suvedha
