### ISSUE TITLE
question about cov mat updates and acceptance

### ISSUE THREAD

**Issue by nblinov** [brinckmann/montepython_public#53]
Hello,

I'm trying to figure out the optimal strategy for a running a scan. 
So far my approach has been to run a model with ~ 1000 points, manually generate covariance matrix and then use that as the proposal density for a longer run, which gives me a good acceptance of 0.2-0.3.
But, e.g. the method mentioned by Thejs in https://github.com/brinckmann/montepython_public/issues/27 skips the first step -- however when I try something like that the acceptance is terrible, even for a very long run (< 0. 01 for a Plik lite 
LCDM run with the default input file).
I don't really understand that - shouldn't the covariance matrix be automatically updated through out the run? why doesn't the acceptance rate approach ~ 0.3?

Thank you!

**Comment by brinckmann** [comment]
Hi,

From your reference to issue #27 it sounds like you are trying to restart a run. It also sounds like you did a short run to produce a covariance matrix. In general, if you do a short run to produce a covmat I would simply re-launch the chains in a new folder and pass the covmat with the `-c` flag, instead of restarting the chains, but this choice really shouldn't make a big difference. Note that if you restart chains in the same folder with the `-r` flag you should manually remove the old chains once they have been successfully copied to the new chains files. The reason for this is that MontePython doesn't know how to distinguish old chains from new ones, and will include the old chains when periodically analyzing the chains to compute a new covmat. This may produce unfortunate results. It is a known issue that we would like to fix.

Since you also mention chains with very poor convergence (< 0.01) the following information may help you:
The problem you describe sometimes occur for Metropolis-Hastings MCMC explorations when initial information is lacking or poorly describes the problem and as a result the run may diverge instead of converging. You would usually try to deal with this in one of three ways:

1. by adjusting the initial magnitude of the jumps, generally towards a smaller value,

2. by using a better initial covariance matrix (does the same as 1., but may also contain information on parameter degeneracies), e.g. as you did by doing a short run to produce a starting covmat,

3. introduce or tighten prior boundaries.

Point 1. can be done either by adjusting the sigma's in the param file or using the -f flag, e.g. -f 2.4 for a perfectly Gaussian likelihood, -f 1.7 for Planck or possibly something lower when lacking initial information. The -f flag adjusts the sigmas for all your parameters, but in some cases only one is problematic and it may be beneficial to adjust them directly in the param file.

Specifically, I would decrease sigmas by a factor 5-10 at a time and try a short run to see if it's going anywhere. In general it is a useful strategy to obtain an initial covariance matrix: if you manage to accumulate some points rather than have the code diverge at <100 accepted points per chain, you can try to compute a covariance matrix to get a better estimate of the sigmas or to get a handle on problematic parameter degeneracies. In some cases increasing the sigmas may be the way to go, e.g. if you are far from the maximum of the likelihood.

Note that providing a covariance matrix will override the sigmas provided in the parameter file (for the parameters given in the covariance matrix) and so you would have to use the -f flag, or directly adjust the diagonal elements of the covariance matrix, remembering that they correspond to sigma^2.

Point 2. you can try to use the --fisher option in order to compute a Fisher matrix (of which the inverse is the covariance matrix), but this method does not work very well if you do not know the maximum of the likelihood or have a non-Gaussian likelihood. You can find more information on that in the MontePython 3 paper: Brinckmann & Lesgourgues 1804.07261.

Finally, you may want to make sure you are using the latest v3.1 of MontePython, as the code saw some significant improvements over v3.0 (and of course v2.2), in particular to the --superupdate option introduced with v3.0, which should help with obtaining convergence in difficult cases.

I hope some of this information will help you!

**Comment by nblinov** [comment]
Hi Thejs, 

Thank you for the detailed response - it is very helpful. 
Starting with an approximate covmat has been my approach as well -- this gives a good acceptance rate as you say. 
I guess I am still puzzled why this is not equivalent to starting without one (i.e. only use the one specified in the default input file), and allowing the automatic updates to take care of adjusting the proposal density. Naively, it would seem that in the limit of a large number of steps these should give the same answer? 
However, this is not what i saw -- the example that experienced poor convergence was ran with v3.1 - 30000 steps were generated and only ~ 200 were accepted. 

Thanks again!

**Comment by brinckmann** [comment]
In principle it should be equivalent, yes, and in most cases it is. However, we impose a requirement that the covariance matrix is only updated automatically if the Gelman-Rubin convergence diagnostic is 0.3 < max(R-1) < 10. This is a somewhat arbitrary choice intended to avoid more prevalent pitfalls of computing very poor covmats early on or excessively updating the covmat later on once a good one has already computed.

However, occasionally the chains may either never reach max(R-1) < 10, and so a new covmat is never computed, or they may reach max(R-1) < 0.3 before a sufficiently good covmat is computed. These cases are rare, but do happen sometimes. Ideally I would add some tests to identify those cases and have the code automatically adjust, but that's not currently implemented. Instead, I can tell you what I do manually. If I notice a run is not making sufficient progress after a certain amount of time I sometimes choose to manually compute a covmat by analyzing the chains with the `--want-covmat` flag while a run is on-going. If the flag `--update` was used (enabled by default) the code will automatically load the new covmat.

Note that this means the chains are no longer Markovian and by default the analyze module will no longer include any part of the chains prior to the covmat update. You can choose to bypass this behavior with the flag `--keep-non-markovian`, often used in combination with e.g. `--keep-fraction 0.7` to mimic the default behavior of GetDist. However, keep in mind that technically Markov chain Monte Carlo runs can only be mathematically proven to converge to the correct result if they are Markovian processes.

This last consideration is really only relevant in the latter case where you may want to compute a better covmat when max(R-1) < 0.3, but where obtaining convergence is slow. Your choices are then to either wait for the run to converge normally (which would be faster with a good covmat) or to include the previous part of the chains as described above and hope the covmat only changed slightly (typically the problem is an incorrect degeneracy direction between two or more parameters leading to inefficient exploration of parameter space) and that including the non-Markovian part of the chains will not bias your results. I cannot provide any guarantees or recommendations for this and you will have to use your own judgement.

**Comment by ivandebono** [comment]
I seem to be having a related problem with my chains, so I won't start a new thread. 

I'm getting this weird behaviour where I start with a good covariance matrix, the chains start to converge after a short while, and the plots start to approach Gaussian posteriors. Then as I accumulate more points, the chains start to diverge.

Analysing them discards all the chains except one (no. 8, with a minimum log likelihood that's different from the rest), and the acceptance rates are way too high.

Here is the log file:

2019-10-28_45000__7.txt	  Number of steps:651	 Steps accepted:210	 acc = 0.32	min(-loglike) = 13.78
2019-10-28_45000__8.txt	  Number of steps:530	 Steps accepted:165	 acc = 0.31	min(-loglike) = 4.65
2019-10-28_45000__4.txt	  Number of steps:536	 Steps accepted:155	 acc = 0.29	min(-loglike) = 13.76
2019-10-28_45000__5.txt	  Number of steps:578	 Steps accepted:200	 acc = 0.35	min(-loglike) = 14.93
2019-10-28_45000__3.txt	  Number of steps:555	 Steps accepted:180	 acc = 0.32	min(-loglike) = 13.52
2019-10-28_45000__2.txt	  Number of steps:567	 Steps accepted:185	 acc = 0.33	min(-loglike) = 15.48
2019-10-28_45000__1.txt	  Number of steps:532	 Steps accepted:175	 acc = 0.33	min(-loglike) = 15.06
2019-10-28_45000__6.txt	  Number of steps:550	 Steps accepted:200	 acc = 0.36	min(-loglike) = 14.52

Should I keep running in the hope of accumulating enough point so the chains start behaving properly, or is there something else I should do?

**Comment by brinckmann** [comment]
Hi Ivan,

Is it possible your posterior distribution could be multimodal?

In `montepython/analyze.py` we have hardcoded a criterium for when to discard chains as having not converged:
`LOG_LKL_CUTOFF = 3`
Usually you won't want to touch this, but e.g. if you are trying to explore a multimodal distribution with Metropolis-Hastings (something it is not very well suited to, in that case I would suggest using PolyChord or MultiNest) you may need to change this number. You can see your chain __8 has a min(-loglike) of 4.65, and all the others are around 13-15. Try setting `LOG_LKL_CUTOFF = 13` to see how your posterior distribution looks when including all chains. Don't forget to change this back for future runs.

Best,
Thejs

**Comment by ivandebono** [comment]
Hi Thejs,

Following your suggestion a few months ago, I had used Polychord to explore this particular model with Planck data. Polychord detected multiple models, depending on the accuracy settings.

However, in this instance I'm using a fiducial model. Does it make statistical sense to use Polychord when the posterior, by construction, is unimodal? 

I had previously run this same model with the same fiducial data, and the chains did converge (albeit very slowly). Now I just changed the value of l_linstep in class to be lower (it should give better accuracy for the model), and used the covariance matrix from the previous runs, and I got the weird behaviour described above.

Your suggestion about the value of log(L) cutoff is probably the only option left.

I spent a lot of time studying the raw output for the chains. This is a plot of one the likelihood values versus parameter value for one of the 'difficult' parameters (from the previous completed run, without removing any of the points, either non-Markovian or burn-in) .
![](https://user-images.githubusercontent.com/22397447/67706510-33830000-f9b9-11e9-8db0-7ee70bc56d28.png)

The spike is near the best-fit value (which is near the fiducial value).  As you can see, the likelihood doesn't drop away smoothly as it would in a near-Gaussian posterior. 

Plotting a histogram with the default 20 bins gives this:
![](https://user-images.githubusercontent.com/22397447/67707039-100c8500-f9ba-11e9-943f-0ba1043f9297.png)

There is a spike, but there is also a secondary peak. I doubt whether Polychord would detect it.

I'll try your LOG_LKL_CUTOFF = 3 suggestion, and report back if I make any progress. Perhaps it could be included as an optional parameter in future versions of MontePython.
