### ISSUE TITLE
How does MontePython handle shooting errors?

### ISSUE THREAD

**Issue by lukashergt** [brinckmann/montepython_public#65]
Hi Thejs (or whoever has experience with this),

could you explain what is causing the frequently occurring **shooting error** (typical error messages down below) and how MontePython handles it?

----------------------------------------------------------------------------------------------------
In CLASS' `source/input.c` it says in lines 322-330:
```c
/* We can do 1 dimensional root finding */
/* If shooting fails, postpone error to background module to play nice with MontePython. */
class_call_try(input_find_root(&xzero,
                               &fevals,
                               &fzw,
                               errmsg),
               errmsg,
               pba->shooting_error,
               shooting_failed=_TRUE_);
```
and the error is then caught in `source/background.c` in lines 630-634:
```c
/** - if shooting failed during input, catch the error here */
class_test(pba->shooting_failed == _TRUE_,
           pba->error_message,
           "Shooting failed, try optimising input_get_guess(). Error message:\n\n%s",
           pba->shooting_error);
```
* **What exactly does "play nice with MontePython" mean here?**

* **How is MontePython supposed to treat a shooting error?** 
  Since it doesn't kill the sampling process, is any parameter combination resulting in a shooting error treated as a rejected point? Is it safe to use a completed run that spawned some shooting errors along the way?

* **Can derived parameters trigger a shooting error?** 
  In issue #55 you suggest switching from `tau_reio` to `z_reio` to bypass the shooting error. However, even after switching to `z_reio` as cosmo parameter I still (albeit less) get shooting errors (at least for runs including curvature). 

----------------------------------------------------------------------------------------------------
The **typical error messages** are:
```c
Error in Class: background_init(L:634) :condition (pba->shooting_failed == _TRUE_) is true; Shooting failed, try optimising input_get_guess(). Error message:

input_init(L:330) :error in input_find_root(&xzero, &fevals, &fzw, errmsg);
=>input_find_root(L:4064) :error in class_fzero_ridder(input_fzerofun_1d, x1, x2, 1e-5*(((fabs(x1))<(fabs(x2))) ? (fabs(x2)) : (fabs(x1)) ), pfzw, &f1, &f2, xzero, fevals, errmsg);
=>class_fzero_ridder(L:3588) :error in (*func)(xm, param, &fm, error_message);
=>input_fzerofun_1d(L:3548) :error in input_try_unknown_parameters(&input, 1, pfzw, output, error_message);
=>input_try_unknown_parameters(L:3725) :error in background_init(&pr,&ba);
=>background_init(L:701) :error in background_solve(ppr,pba);
=>background_solve(L:1654) :condition ((tau_end-tau_start)/tau_start < ppr->smallest_allowed_variation) is true; integration step: relative change in time =2.074536e-16 < machine precision : leads either to numerical error or infinite loop
```
or
```c
Error in Class: background_init(L:634) :condition (pba->shooting_failed == _TRUE_) is true; Shooting failed, try optimising input_get_guess(). Error message:

input_init(L:330) :error in input_find_root(&xzero, &fevals, &fzw, errmsg);
=>input_find_root(L:4037) :error; input_fzerofun_1d(L:3548) :error in input_try_unknown_parameters(&input, 1, pfzw, output, error_message);
=>input_try_unknown_parameters(L:3725) :error in background_init(&pr,&ba);
=>background_init(L:701) :error in background_solve(ppr,pba);
=>background_solve(L:1672) :error in generic_integrator(background_derivs, tau_start, tau_end, pvecback_integration, &bpaw, ppr->tol_background_integration, ppr->smallest_allowed_variation, &gi);
=>generic_integrator(L:112) :error in rkqs(&x, h, eps, &hdid, &hnext, derivs, parameters_and_workspace_for_derivs, pgi);
=>rkqs(L:156) :condition (xnew == *x) is true; stepsize underflow at x=9.338054e+03
```

**Comment by brinckmann** [comment]
Hi Lukas,

Sorry for not getting back to you sooner. If MontePython receives an error from class it should reject the proposed step and propose a new one. As such, shooting errors are not usually (but not guaranteed not to be) a problem, as they are not typically a systematic problem, but rather a random one (i.e. not correlated with parameters). A common parameter to receive shooting errors with is tau_reio, as you mention, in which an easy trick is to switch to z_reio (putting tau_reio as a derived parameter, if so desired).

For other parameters (e.g. extended models) encountering shooting errors I don't have a good rule of thumb, but contrary to my previous argument it can in fact be due to exploring a part of parameter space to which the code is not well tuned, in which case it would be best to introduce prior bounds eliminating undesired parts of parameter space (which are usually low probability parts of parameter space anyway, although this should be verified).

Best,
Thejs
