### ISSUE TITLE
Indentation error in mcmc.py

### ISSUE THREAD

**Issue by ivandebono** [brinckmann/montepython_public#66]
I'm going through the code to make it compatible with Python 3.7. The file mcmc.py, which seems to be the work of several collaborators, has some indentation errors which I haven't been able to resolve. 

In line 516, the tabbed line (4 spaces) `if command_line.update:` is followed by a double indent (8 spaces). This is repeated in line 530. 

There is an inconsistent use of tabs. Some are 4 spaces, some are 8, and it is hard to know which is which.

**Comment by brinckmann** [comment]
Hi Ivan,

@schoeneberg was working on a python 3 compatible MontePython version, perhaps you can get in touch with him before spending more time on it. I think he finished it but that we opted not to make it the default because the Planck likelihoods are not Python 3 compatible.

As for your specific question, the lines should be displayed correctly in terms of indentations if you look at the github file: https://github.com/brinckmann/montepython_public/blob/master/montepython/mcmc.py

I.e. you can refer to this file when indentations are inconsistent. In the meantime thanks for pointing it out and I'll fix it in the next version.

Best,
Thejs

**Comment by ivandebono** [comment]
Hi Thejs,

Thank you for the reply. 

There is one other possible bug. In line 666, the parameter "stop-after-update" is used. This should probably be "stop_after_update" (i.e. underscores, not hyphens or minus signs). But even if the naming were consistent, the parameter doesn't seem to be defined anywhere in the code (it's a True or False parameter).

**Comment by brinckmann** [comment]
Thanks! This was a feature that we decided to cut because it wasn't useful. I see it wasn't removed properly (and also still appears in the parser_mp.py as well).

**Comment by brinckmann** [comment]
Thanks I fixed these issues.
