### ISSUE TITLE
polarization data

### ISSUE THREAD

**Issue by mahtaparsa** [brinckmann/montepython_public#76]
In order to constrain cosmological model with Planck polarization data, which likelihood should we use in .param file?
Planck_lowl_EE, Planck_lowl_BB, or Planck_lowl_EEBB, or all of these likelihoods?

**Comment by brinckmann** [comment]
Hi,

It depends on what you need. Do you want to use only polarization, i.e. no temperature data? Do you need B-modes as well as E-modes? Do you want highl or only lowl?

The Planck [wiki page on CMB spectra and likelihoods](https://wiki.cosmos.esa.int/planck-legacy-archive/index.php/CMB_spectrum_%26_Likelihood_Code) explains the details of the different likelihoods. In order to match up our likelihood names with the ones in there you can look at the .data file, e.g.
`montepython/likelihoods/Planck_lowl_EE/Planck_lowl_EE.data`
which contains the path variable:
`Planck_lowl_EE.path_clik = os.path.join(data.path['clik'], '../../../baseline/plc_3.0/low_l/simall/simall_100x143_offlike5_EE_Aplanck_B.clik')`
From here you can see the name of the clik file, in this case `simall_100x143_offlike5_EE_Aplanck_B.clik`
You can then use this to search the wiki and read details about the likelihood.

A typical example setup with all of temperature, polarisation and lensing would be the
`input/base2018TTTEEE_lensing.param`
which uses the likelihoods
`['Planck_highl_TTTEEE', 'Planck_lowl_EE', 'Planck_lowl_TT', 'Planck_lensing']`
Here the polarisation information is contained in Planck_highl_TTTEEE for highl and Planck_lowl_EE for lowl. Note that there are no B-modes included.

Best,
Thejs

**Comment by mahtaparsa** [comment]
And there is another question:
In default.conf.template file, for path['clik'] should we write
root+'/Planck/code/plc_3.0/plc-3.01/'
or
root+'/Planck/baseline/plc_3.0/' ?
Because the Planck data (highl, lowl and lensing files) are in the latter directory.
