### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by ghost** [brinckmann/montepython_public#77]
Hello everyone,

I have downloaded montepython and follow all the installation procedure without having any problem, I have confirmed I have a correct version of python and all the other things needed. The problem is that when I run it have the following error segmentation fault:
`python montepython/MontePython.py run -o test -p example.param`

`Running Monte Python v3.2.0`

`with CLASS v2.7.2
 /!\ Running CLASS from a non version-controlled repository`

`Testing likelihoods for:
 -> fake_planck_bluebook`
`Initialised likelihood_mock_cmb with following options:
  unlensed_clTTTEEE is False
  Bmodes is False
  delensing is False
  LensingExtraction is False
  neglect_TD is True
  ExcludeTTTEEE is False
  OnlyTT is False`

`Creating test/2019-10-02_10__1.txt`

`Deduced starting covariance matrix:`
`['omega_b', 'omega_cdm', 'n_s', 'A_s', 'h', 'tau_reio']`
`[[2.56e-04 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]`
 `[0.00e+00 2.56e-06 0.00e+00 0.00e+00 0.00e+00 0.00e+00]`
` [0.00e+00 0.00e+00 1.60e-05 0.00e+00 0.00e+00 0.00e+00]`
` [0.00e+00 0.00e+00 0.00e+00 1.44e-03 0.00e+00 0.00e+00]`
` [0.00e+00 0.00e+00 0.00e+00 0.00e+00 4.22e-05 0.00e+00]`
` [0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.94e-05]]`

`Update routine is enabled with value 50 (recommended: 50)`
`This number is rescaled by cycle length 6 (N_slow + f_fast * N_fast) to 300`
`Segmentation fault (core dumped)`

I do not even change anything and I do not know what is wrong.
If anyone could help it will be great
Thanks!!

**Comment by brinckmann** [comment]
Hi,

Can you check that you can run CLASS? I.e. go to your CLASS directory and write ./class explanatory.ini

Best,
Thejs

**Comment by DCarlosHe** [comment]
Thanks for your reply.

It seems that I have the same problem while running explanatory.ini but It runs perfectly if I use another .ini I created before. The only different (apart from the change in the values of parameters, not even big) is a new parameter.

**Comment by brinckmann** [comment]
Aha! That gives us an indication of what is wrong. Your modified CLASS version hasn't been set up to run without your new parameter. So you have two options, either modify CLASS further where it doesn't crash if the new parameter is not set, or set it in your parameter file.

Did you already add the parameter to the wrapper? If so you can set it directly in MontePython. If you want to vary the parameter, you set it as a cosmo parameter in your param file like the usual cosmological parameters, where the name is simply the name of your parameter in CLASS, i.e. something like:
`data.parameters['new_parameter']  = [0.0, None, None, 0.1,     1,   'cosmo']`
where you set the mean value (first entry in the list) and 1-sigma value (second to last, used for proposing jumps), as well as possible the lower and upper boundary instead of the two None.

Or you can fix it using cosmo_arguments:
`data.cosmo_arguments['new_parameter'] = 0.0`

For more information, check out the [course page on Julien Lesgourgues' website](https://lesgourg.github.io/courses.html), where you can find my MontePython lecture notes explaining this.

Best,
Thejs

**Comment by DCarlosHe** [comment]
Thanks  again for the answer, and sorry if the questions are so easy (first time using MontePython).

I have added in the example.param file  a line like that. I am a bit confused I thought wrongly that after doing make clean; make; everything should work so what I have to do to add the parameter to the wrapper?

Thanks for your help!!

**Comment by DCarlosHe** [comment]
In fact I wrote on the file cclassy.pxd in the cdef struct background this:

`double parameteramodel`

and in MontePython in example.param this:

`data.parameters['parameteramodel']  = [1.0,    -1,-1, 0.1,1,     'cosmo']`

I do not know what I am missing...

**Comment by brinckmann** [comment]
Mind your boundaries, they're both set to -1, which doesn't make a lot of sense. It doesn't work if you change that?

Best,
Thejs

**Comment by DCarlosHe** [comment]
If they are set to -1 this means that that are irrelevant?
Anyway I write 
`data.parameters['parameteramodel']  = [1.0,    0,10, 0.1,1,     'cosmo']` and it is the same.

What it is very strange for me is that in the param file I have:
#Cosmological parameters list
data.parameters['omega_b'] 	= [2.249,  -1,-1, 0.016, 0.01,'cosmo']
data.parameters['omega_cdm'] 	= [0.1120, -1,-1, 0.0016,1,   'cosmo']
data.parameters['n_s']       	= [0.963,  -1,-1, 0.004, 1,   'cosmo']
data.parameters['A_s']       	= [2.42,   -1,-1, 0.038, 1e-9,'cosmo']
data.parameters['h']         	= [0.703,  -1,-1, 0.0065,1,   'cosmo']
data.parameters['tau_reio']    	= [0.085,  -1,-1, 0.0044,1,   'cosmo']
data.parameters['parameteramodel']  = [1.0,    0,10, 0.1,1,     'cosmo']

but when doing `python montepython/MontePython.py run -o test -p example.param` it does not appear parameteramodel in:
....
`Deduced starting covariance matrix:`
`['omega_b', 'omega_cdm', 'n_s', 'A_s', 'h', 'tau_reio']`
`[[2.56e-04 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]`
`[0.00e+00 2.56e-06 0.00e+00 0.00e+00 0.00e+00 0.00e+00]`
`[0.00e+00 0.00e+00 1.60e-05 0.00e+00 0.00e+00 0.00e+00]`
`[0.00e+00 0.00e+00 0.00e+00 1.44e-03 0.00e+00 0.00e+00]`
`[0.00e+00 0.00e+00 0.00e+00 0.00e+00 4.22e-05 0.00e+00]`
`[0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 1.94e-05]]`
....
it should have also a column with parameteramodel?


Many thanks for your help!

**Comment by brinckmann** [comment]
It depends what you're trying to do. Setting both boundaries to -1 should fix the parameter, so it's the same as passing the parameter with `data.cosmo_arguments['parameteramodel'] = 1.0`, but if that's what you were trying to do I would recommend using cosmo_arguments as that's what it is designed for. If you want to vary the parameter you have to set reasonable boundaries, this could be e.g. `None, None` if you want to set no boundaries or `0, 10` as you did in your last example.

The reason you aren't seeing a column with parameteramodel in the last case is because you are running in the same directory "test", in which case it takes the log.param from that directory instead of the input param file. Your old param file didn't have parameteramodel varying and so it won't vary it. You need to run in a new directory instead.

Best,
Thejs

**Comment by DCarlosHe** [comment]
Yes, in another directory I have the new parameter in a column.
But again I continue to have the `Segmentation fault (core dumped)` problem.

**Comment by DCarlosHe** [comment]
Maybe is nothing but I noticed a couple of things:

- After `$make` there is the following warnings about "using deprecated NumPy API":
```
n file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1822,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /mnt/Datos/usuario/Escritorio/code/class2/python/../python/classy.c:598:python setup.py install --user
running install
running build
running build_ext
skipping '/mnt/Datos/usuario/Escritorio/code/class2/python/../python/classy.c' Cython extension (up-to-date)
running install_lib
running install_egg_info
Removing /home/usuario/.local/lib/python2.7/site-packages/classy-2.7.2.egg-info
Writing /home/usuario/.local/lib/python2.7/site-packages/classy-2.7.2.egg-info

/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
creating build/lib.linux-x86_64-2.7

```
- When doing `$python setup.py` build and `$python setup.py install --user` some "skipping":

```
$python setup.py build
running build
running build_ext
skipping '/mnt/Datos/usuario/Escritorio/code/class2/python/../python/classy.c' Cython extension (up-to-date)

```

```
$python setup.py install --user
running install
running build
running build_ext
skipping '/mnt/Datos/usuario/Escritorio/code/class2/python/../python/classy.c' Cython extension (up-to-date)
running install_lib
running install_egg_info
Removing /home/usuario/.local/lib/python2.7/site-packages/classy-2.7.2.egg-info
Writing /home/usuario/.local/lib/python2.7/site-packages/classy-2.7.2.egg-info

```
  
Maybe you know if it is related with the problem I am having...

**Comment by brinckmann** [comment]
Hi,

MontePython doesn't usually produce seg faults, these will usually originate in e.g. CLASS or MultiNest. It could be as you say there's something going on with the numpy installation, as this could in principle also return seg faults, but this seems unlikely.

Before proceeding, can you please try to install a clean CLASS version with no modifications and run MontePython with that? If it returns no issues I would assume the problem is with your modified CLASS version.

Best,
Thejs

**Comment by DCarlosHe** [comment]
In fact I checked it with a non modified version of CLASS and it works. Also the CLASS modified version works perfectly.

I think there is something  I am not doing while passing the new parameter to the wrapper. I modified the file cclassy.pxd just adding in `cdef struct background:` another line `double parameteramodel`.
Also following another indications I modified the classy.pyx by adding in 
```
def get_current_derived_parameters(self, names):
        if type(names) != type([]):
            raise TypeError("Deprecated")
        derived = {}
        for name in names:
```
a line like this
```
elif name == 'parameteramodel':
                value = self.ba.parameteramodel
```
but it does not work.

Am I forgetting to do anything more needed to introduce a new parameter in the wrapper module?
