### ISSUE TITLE
plot 3σ  contour

### ISSUE THREAD

**Issue by kangjg** [brinckmann/montepython_public#8]
Hi,all
    How to plot 3σ  contours  in 'info' analysis ,and modify analysis codes? 
 thanks！

**Comment by brinckmann** [comment]
Hi,
You have to make a small change in `montepython/analyze.py`
Lines 851-853 explains:
```
                        # plotting contours, using the ctr_level method (from Karim                                                                                       
                        # Benabed). Note that only the 1 and 2 sigma contours are                                                                                         
                        # displayed (due to the line with info.levels[:2])  
```
This means you want to change lines 867 and 881 for filled contours or line 897 for line contours, i.e. change `info.levels[:2]` to `info.levels[:3]` on line 867 or 897 in order to get three sigma filled or line contours contours and `info.levels[1:2]` to `info.levels[2:3]` on line 881 to move the solid line contour on the filled contour plot from two sigma to three sigma.
Best,
Thejs

**Comment by kangjg** [comment]
Respected Thejs ,thank  you instructions, I have modified analyse.py file  as you explained, and plot 3σ contours successfully with 'info' command . 
Best，
Kang

**Comment by am610** [comment]
what would be the command, if I would be interested in plotting only the 1sigma contours ?
