### ISSUE TITLE
Info for terminated jobs

### ISSUE THREAD

**Issue by miguelzuma** [brinckmann/montepython_public#81]
Hi,

I noticed that jobs that end abruptly (typically because of time allocation) have two problems:
* no model.log/covmat/bestfit are generated. While bestfit/covmat can be generated latter, the info on the acceptance rate is lost
* if using the restart option, the old chains are not automatically removed ( only the first of the chains is removed, even if the job ends on time and the above operations are performed).

I'm wondering if there  could be an option to update model.log every number of steps. 

This might be desirable: I find myself performing multiple (relatively short ~4h) runs, using the --restart option to increasingly grow the chains. This is mainly due to the cluster allocation preferences (my cluster gives very low preference to long runs). For this reason, I want to maximize the amount of points in each chain before the job ends (by the allocation time).

Thanks,

Miguel

**Comment by brinckmann** [comment]
Hi Miguel,

I'm not sure I understand. Isn't a model.log file generated automatically when analyzing the chains? Also, isn't it created automatically every --update number of steps? If not that would be a nice feature to add, as certainly the model.log file getting periodically updated would be useful.

The issue with the restart option not properly removing the files is a known issue. Ideally it would be removed upon successful copy at the start when restarting a run, as it interferes with the restarted run otherwise (or more specifically, with the --update and --superupdate features). When I was fixing the restart option (it used to only copy the first file, not the rest) I couldn't easily figure out how to do this. I'd welcome to suggestions!

Best,
Thejs

**Comment by ivandebono** [comment]
> When I was fixing the restart option (it used to only copy the first file, not the rest) I couldn't easily figure out how to do this. I'd welcome to suggestions!
> 

I think the cleanest way would be:

- Upon succesful copy of a file, rename the original (e.g. by adding a non-numeric suffix to the file name)
- Delete all files containing the suffix at the end of the run.

**Comment by brinckmann** [comment]
That's a good idea, thanks! I'll look to implement this for the next release.

Best,
Thejs
